import type { Section } from "../types";

export const advancedRegexSection: Section = {
  id: "advanced-regex",
  title: "Regex Mastery",
  emoji: "🧙",
  blurb: "Anchors, lookarounds, named groups, replacers.",
  levels: [
    {
      id: "rx-1",
      title: "Anchors & Quantifiers",
      emoji: "⚓",
      difficulty: 2,
      theory: "`^` start, `$` end. `+` one-or-more, `*` zero-or-more, `?` optional, `{n,m}` range.",
      goal: "Build regex `re` matching strings that are exactly digits (1+). `re.test('123')` true, `re.test('1a')` false.",
      starterCode: `// const re = /.../;\n`,
      steps: [
        { label: "matches '123'", test: `re.test('123') === true` },
        { label: "rejects '1a'", test: `re.test('1a') === false` },
        { label: "rejects empty", test: `re.test('') === false` },
      ],
      hints: ["/^\\d+$/"],
      solution: `const re = /^\\d+$/;`,
      quiz: [{ q: "Without ^ and $, /\\d+/ matches…", options: ["only full strings", "any substring of digits", "nothing", "errors"], answer: 1 }],
    },
    {
      id: "rx-2",
      title: "Character Classes",
      emoji: "🔡",
      difficulty: 2,
      theory: "`[abc]` any of a/b/c. `[a-z]` range. `[^...]` negation. Common shortcuts: `\\d \\w \\s`.",
      goal: "Regex `re` matching valid simple identifiers: starts with letter or _, then any letters/digits/_.",
      starterCode: `// const re = /.../;\n`,
      steps: [
        { label: "matches 'foo_bar1'", test: `re.test('foo_bar1') === true` },
        { label: "rejects '1abc'", test: `re.test('1abc') === false` },
        { label: "rejects 'a-b'", test: `re.test('a-b') === false` },
      ],
      hints: ["/^[A-Za-z_][A-Za-z0-9_]*$/"],
      solution: `const re = /^[A-Za-z_][A-Za-z0-9_]*$/;`,
      quiz: [{ q: "\\w is equivalent to…", options: ["[a-z]", "[A-Za-z0-9_]", "[ \\t]", "any char"], answer: 1 }],
    },
    {
      id: "rx-3",
      title: "Named Groups",
      emoji: "🏷️",
      difficulty: 3,
      theory: "Use `(?<name>...)` to capture into named groups. Access via `match.groups.name`.",
      goal: "Parse `'2025-04-24'` into `{year, month, day}` strings using a regex with named groups. Store in `parts`.",
      starterCode: `const s = '2025-04-24';\n// const parts = s.match(/.../).groups;\n`,
      steps: [
        { label: "year/month/day correct", test: `parts.year==='2025' && parts.month==='04' && parts.day==='24'` },
      ],
      hints: ["/(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})/"],
      solution: `const s='2025-04-24'; const parts = s.match(/(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})/).groups;`,
      quiz: [{ q: "Named groups appear under match.…", options: ["named", "groups", "captures", "indices"], answer: 1 }],
    },
    {
      id: "rx-4",
      title: "Lookahead",
      emoji: "👀",
      difficulty: 3,
      theory: "`(?=...)` positive lookahead — match only if followed by, without consuming.",
      goal: "Regex `re` matching numbers immediately followed by 'px'. `'12px 7em 5px'.match(re)` === ['12','5'].",
      starterCode: `// const re = /.../g;\n// const out = '12px 7em 5px'.match(re);\n`,
      steps: [
        { label: "out is ['12','5']", test: `JSON.stringify(out) === '["12","5"]'` },
      ],
      hints: ["/\\d+(?=px)/g"],
      solution: `const re = /\\d+(?=px)/g; const out = '12px 7em 5px'.match(re);`,
      quiz: [{ q: "Lookahead consumes characters?", options: ["yes", "no — zero-width", "only with g flag", "depends"], answer: 1 }],
    },
    {
      id: "rx-5",
      title: "Replace with Function",
      emoji: "🔧",
      difficulty: 3,
      theory: "`str.replace(re, fn)` — fn receives match + groups and returns the replacement string.",
      goal: "Convert any number in a string to its double. `'a 3 b 4'.replace(re, fn)` → `'a 6 b 8'` stored in `out`.",
      starterCode: `const s = 'a 3 b 4';\n// const out = s.replace(/\\d+/g, m => ...);\n`,
      steps: [
        { label: "out === 'a 6 b 8'", test: `out === 'a 6 b 8'` },
      ],
      hints: ["m => Number(m) * 2"],
      solution: `const s='a 3 b 4'; const out = s.replace(/\\d+/g, m => Number(m)*2);`,
      quiz: [{ q: "Replacer fn first arg is…", options: ["index", "the full match", "the input", "groups"], answer: 1 }],
    },
  ],
};
