import type { Section } from "../types";

export const algorithmsSection: Section = {
  id: "algorithms",
  title: "Algorithms Lab",
  emoji: "🧮",
  blurb: "Sorting, searching, and classic problems.",
  levels: [
    {
      id: "alg-1",
      title: "Reverse a String",
      emoji: "🔄",
      difficulty: 1,
      theory: "Many ways: split/reverse/join, loop, recursion. Pick the clearest.",
      goal: "Function `reverse(s)` returns the reversed string.",
      starterCode: `function reverse(s){\n  // return reversed\n}\n`,
      steps: [
        { label: "reverse('hello') === 'olleh'", test: `reverse('hello') === 'olleh'` },
        { label: "reverse('') === ''", test: `reverse('') === ''` },
        { label: "reverse('a') === 'a'", test: `reverse('a') === 'a'` },
      ],
      hints: ["s.split('').reverse().join('')"],
      solution: `function reverse(s){ return s.split('').reverse().join(''); }`,
      quiz: [{ q: "Why split('') and not split()?", options: ["faster", "split() returns the whole string in one element", "they're equal", "syntax"], answer: 1 }],
    },
    {
      id: "alg-2",
      title: "Palindrome Check",
      emoji: "🪞",
      difficulty: 2,
      theory: "A palindrome reads the same forwards and backwards. Normalize case/punctuation if needed.",
      goal: "Function `isPalindrome(s)` (case-insensitive, ignore non-alphanumerics).",
      starterCode: `function isPalindrome(s){\n  // normalize then compare\n}\n`,
      steps: [
        { label: "'Racecar' true", test: `isPalindrome('Racecar') === true` },
        { label: "'A man, a plan, a canal: Panama' true", test: `isPalindrome('A man, a plan, a canal: Panama') === true` },
        { label: "'hello' false", test: `isPalindrome('hello') === false` },
      ],
      hints: ["const c = s.toLowerCase().replace(/[^a-z0-9]/g,''); return c === c.split('').reverse().join('');"],
      solution: `function isPalindrome(s){ const c=s.toLowerCase().replace(/[^a-z0-9]/g,''); return c===c.split('').reverse().join(''); }`,
      quiz: [{ q: "Common palindrome trick:", options: ["sort", "reverse and compare", "hash map", "regex only"], answer: 1 }],
    },
    {
      id: "alg-3",
      title: "FizzBuzz",
      emoji: "🥤",
      difficulty: 1,
      theory: "Classic interview warm-up. Multiples of 3 → 'Fizz', 5 → 'Buzz', both → 'FizzBuzz'.",
      goal: "Function `fizzbuzz(n)` returns an array length n with the right strings/numbers.",
      starterCode: `function fizzbuzz(n){\n  // return array length n\n}\n`,
      steps: [
        { label: "first 5 correct", test: `JSON.stringify(fizzbuzz(5)) === '[1,2,"Fizz",4,"Buzz"]'` },
        { label: "15 → 'FizzBuzz'", test: `fizzbuzz(15)[14] === 'FizzBuzz'` },
      ],
      hints: ["i%15===0 ? 'FizzBuzz' : i%3===0 ? 'Fizz' : i%5===0 ? 'Buzz' : i"],
      solution: `function fizzbuzz(n){ return Array.from({length:n}, (_,k)=>{ const i=k+1; return i%15===0?'FizzBuzz':i%3===0?'Fizz':i%5===0?'Buzz':i; }); }`,
      quiz: [{ q: "Check 15 first because…", options: ["it's faster", "to avoid 3 and 5 short-circuiting", "convention", "no reason"], answer: 1 }],
    },
    {
      id: "alg-4",
      title: "Binary Search",
      emoji: "🎯",
      difficulty: 3,
      theory: "On a SORTED array, repeatedly halve the range. O(log n).",
      goal: "Function `bsearch(arr, target)` returns the index of target or -1. Iterative.",
      starterCode: `function bsearch(arr, target){\n  // return index or -1\n}\n`,
      steps: [
        { label: "find middle", test: `bsearch([1,3,5,7,9], 5) === 2` },
        { label: "missing → -1", test: `bsearch([1,3,5,7,9], 6) === -1` },
        { label: "find first", test: `bsearch([10,20,30], 10) === 0` },
        { label: "find last", test: `bsearch([10,20,30], 30) === 2` },
      ],
      hints: ["let lo=0, hi=arr.length-1; while(lo<=hi){ const m=(lo+hi)>>1; if(arr[m]===t) return m; arr[m]<t? lo=m+1 : hi=m-1; }"],
      solution: `function bsearch(arr,t){ let lo=0,hi=arr.length-1; while(lo<=hi){ const m=(lo+hi)>>1; if(arr[m]===t) return m; arr[m]<t?lo=m+1:hi=m-1; } return -1; }`,
      quiz: [{ q: "Binary search needs the array to be…", options: ["unique", "sorted", "small", "numeric"], answer: 1 }],
    },
    {
      id: "alg-5",
      title: "Group By",
      emoji: "🗂️",
      difficulty: 2,
      theory: "Group items by a key — common data-shaping op. Use reduce into an object.",
      goal: "Function `groupBy(arr, keyFn)` returns an object: keys = keyFn(item), values = arrays of items.",
      starterCode: `function groupBy(arr, keyFn){\n  // reduce into object\n}\n`,
      steps: [
        {
          label: "groups by parity",
          test: `JSON.stringify(groupBy([1,2,3,4], n => n%2 ? 'odd' : 'even')) === JSON.stringify({odd:[1,3], even:[2,4]})`,
        },
      ],
      hints: ["arr.reduce((acc,x)=>{ const k=keyFn(x); (acc[k] ||= []).push(x); return acc; }, {})"],
      solution: `function groupBy(arr,keyFn){ return arr.reduce((acc,x)=>{ const k=keyFn(x); (acc[k] ||= []).push(x); return acc; }, {}); }`,
      quiz: [{ q: "`x ||= y` means…", options: ["assign y always", "assign y if x is falsy", "compare", "delete x"], answer: 1 }],
    },
  ],
};
