import type { Section } from "../types";

const SHELL_CSS = `
  body{margin:0;font-family:'JetBrains Mono',monospace;background:#0f0f17;color:#f5f5dc;padding:24px;}
  .stage{display:flex;align-items:center;justify-content:center;gap:14px;min-height:240px;}
`;

export const cssBasicsSection: Section = {
  id: "css-basics",
  title: "CSS Foundations",
  emoji: "🎨",
  blurb: "Selectors, the box model, color and units.",
  levels: [
    {
      id: "css-1",
      title: "Color the Box",
      emoji: "🟪",
      difficulty: 1,
      language: "css",
      theory: "Class selectors start with `.classname`. Use `background-color` and `color` to style.",
      goal: "Make .box have a hot pink background and white text.",
      previewHtml: `<div class="stage"><div class="box">Hello</div></div>`,
      previewCss: `${SHELL_CSS}\n.box{padding:30px 40px;border-radius:12px;font-size:24px;font-weight:700;}`,
      starterCode: `.box {\n  /* your styles */\n}\n`,
      steps: [
        { label: "Background is hot pink", test: `getComputedStyle(document.querySelector('.box')).backgroundColor === 'rgb(255, 105, 180)'` },
        { label: "Text is white", test: `getComputedStyle(document.querySelector('.box')).color === 'rgb(255, 255, 255)'` },
      ],
      hints: ["background: hotpink; color: white;"],
      solution: `.box {\n  background: hotpink;\n  color: white;\n}`,
      quiz: [{ q: "What's the class selector for .btn?", options: ["#btn", ".btn", "btn", "*btn"], answer: 1 }],
    },
    {
      id: "css-2",
      title: "Box Model",
      emoji: "📦",
      difficulty: 1,
      language: "css",
      theory: "Every element is a box: content + padding + border + margin. `box-sizing: border-box` makes width include padding & border.",
      goal: "Give .card 24px padding, a 4px solid gold border, and 16px border-radius.",
      previewHtml: `<div class="stage"><div class="card">Card</div></div>`,
      previewCss: `${SHELL_CSS}\n.card{background:#1a1a24;color:#facc15;font-weight:700;}`,
      starterCode: `.card {\n  /* padding, border, border-radius */\n}\n`,
      steps: [
        { label: "Padding 24px", test: `getComputedStyle(document.querySelector('.card')).paddingTop === '24px'` },
        { label: "4px solid gold border", test: `const s=getComputedStyle(document.querySelector('.card')); return s.borderTopWidth==='4px' && s.borderTopStyle==='solid' && s.borderTopColor==='rgb(255, 215, 0)';` },
        { label: "Border-radius 16px", test: `getComputedStyle(document.querySelector('.card')).borderTopLeftRadius === '16px'` },
      ],
      hints: ["padding:24px; border:4px solid gold; border-radius:16px;"],
      solution: `.card {\n  padding: 24px;\n  border: 4px solid gold;\n  border-radius: 16px;\n}`,
      quiz: [{ q: "Which is OUTSIDE the border?", options: ["padding", "margin", "content", "outline-width"], answer: 1 }],
    },
    {
      id: "css-3",
      title: "Hover State",
      emoji: "👆",
      difficulty: 2,
      language: "css",
      theory: "Pseudo-classes like `:hover` apply styles on user interaction. Combine with `transition` for smoothness.",
      goal: "On .btn:hover, make the background 'crimson'. Also add a 0.3s transition on background-color.",
      previewHtml: `<div class="stage"><button class="btn">Hover me</button></div>`,
      previewCss: `${SHELL_CSS}\n.btn{padding:14px 28px;border:0;border-radius:8px;background:#facc15;color:#111;font-size:18px;font-weight:700;cursor:pointer;}`,
      starterCode: `.btn {\n  transition: /* ... */;\n}\n\n.btn:hover {\n  /* ... */\n}\n`,
      steps: [
        { label: "transition includes background-color 0.3s", test: `const t=getComputedStyle(document.querySelector('.btn')).transition; return /background-color/.test(t) && /0\\.3s/.test(t);` },
        {
          label: "Hover background is crimson",
          test: `const sheet=document.getElementById('__user_css').sheet; let found=false; for (const r of sheet.cssRules){ if(r.selectorText && r.selectorText.includes(':hover') && r.style.backgroundColor && (r.style.backgroundColor==='crimson' || r.style.backgroundColor==='rgb(220, 20, 60)')) found=true; } return found;`,
          hint: "Add .btn:hover { background: crimson; }",
        },
      ],
      hints: [".btn{ transition: background-color .3s; }", ".btn:hover{ background: crimson; }"],
      solution: `.btn {\n  transition: background-color .3s;\n}\n.btn:hover {\n  background: crimson;\n}`,
      quiz: [{ q: ":hover is a…", options: ["pseudo-element", "pseudo-class", "media query", "selector list"], answer: 1 }],
    },
    {
      id: "css-4",
      title: "Specificity",
      emoji: "🎯",
      difficulty: 2,
      language: "css",
      theory: "Specificity ranking: inline > id (#) > class (.) > tag. The MORE specific selector wins when rules conflict.",
      goal: "Without changing the HTML, make the text inside #target turn 'limegreen'. There's already a generic rule fighting you — beat it!",
      previewHtml: `<div class="stage"><p id="target" class="text">Color me lime!</p></div>`,
      previewCss: `${SHELL_CSS}\n.text{color:gray;font-size:24px;font-weight:700;}`,
      starterCode: `/* Use a more specific selector */\n`,
      steps: [
        { label: "#target text is limegreen", test: `getComputedStyle(document.getElementById('target')).color === 'rgb(50, 205, 50)'` },
      ],
      hints: ["#target { color: limegreen; }"],
      solution: `#target { color: limegreen; }`,
      quiz: [{ q: "Highest natural specificity?", options: [".class", "tag", "#id", "*"], answer: 2 }],
    },
    {
      id: "css-5",
      title: "Pseudo-elements",
      emoji: "✨",
      difficulty: 2,
      language: "css",
      theory: "`::before` and `::after` insert generated content. They need a `content` property — even if empty ('').",
      goal: "Add a ⭐ before .badge using ::before. Give it 6px right margin.",
      previewHtml: `<div class="stage"><span class="badge">Pro</span></div>`,
      previewCss: `${SHELL_CSS}\n.badge{padding:6px 12px;border-radius:999px;background:#facc15;color:#111;font-weight:700;}`,
      starterCode: `.badge::before {\n  /* content + margin */\n}\n`,
      steps: [
        {
          label: "::before content is a star",
          test: `const cs=getComputedStyle(document.querySelector('.badge'),'::before'); return /★|⭐/.test(cs.content) || cs.content.includes('star');`,
        },
        {
          label: "::before has 6px right margin",
          test: `getComputedStyle(document.querySelector('.badge'),'::before').marginRight === '6px'`,
        },
      ],
      hints: [".badge::before{ content:'⭐'; margin-right:6px; }"],
      solution: `.badge::before {\n  content: '⭐';\n  margin-right: 6px;\n}`,
      quiz: [{ q: "Pseudo-elements need which property?", options: ["display", "content", "before", "src"], answer: 1 }],
    },
    {
      id: "css-6",
      title: "Variables (Custom Properties)",
      emoji: "🎨",
      difficulty: 2,
      language: "css",
      theory: "CSS variables: `--name: value` on a selector, `var(--name)` to use. They cascade and can be overridden per-component.",
      goal: "Define `--brand: #22d3ee` on `:root` and use it for .btn's background.",
      previewHtml: `<div class="stage"><button class="btn">Click</button></div>`,
      previewCss: `${SHELL_CSS}\n.btn{padding:12px 24px;border:0;border-radius:8px;font-weight:700;color:#111;font-size:18px;cursor:pointer;}`,
      starterCode: `:root {\n  /* --brand */\n}\n.btn {\n  /* use var() */\n}\n`,
      steps: [
        { label: "--brand defined as #22d3ee", test: `getComputedStyle(document.documentElement).getPropertyValue('--brand').trim().toLowerCase() === '#22d3ee'` },
        { label: "Button background uses var", test: `getComputedStyle(document.querySelector('.btn')).backgroundColor === 'rgb(34, 211, 238)'` },
      ],
      hints: [":root{ --brand: #22d3ee; }", ".btn{ background: var(--brand); }"],
      solution: `:root {\n  --brand: #22d3ee;\n}\n.btn {\n  background: var(--brand);\n}`,
      quiz: [{ q: "How do you READ a CSS var?", options: ["read()", "var()", "$()", "get()"], answer: 1 }],
    },
    {
      id: "css-7",
      title: "Position Absolute",
      emoji: "📍",
      difficulty: 2,
      language: "css",
      theory: "`position: absolute` removes from flow and positions relative to the nearest *positioned* ancestor (often `position: relative`).",
      goal: "Anchor the .badge to the top-right corner of .card (top: 8px; right: 8px).",
      previewHtml: `<div class="stage"><div class="card">Card<span class="badge">NEW</span></div></div>`,
      previewCss: `${SHELL_CSS}\n.card{position:relative;width:200px;height:120px;background:#1a1a24;color:#fff;padding:14px;border-radius:10px;}\n.badge{background:#ef4444;color:#fff;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:700;}`,
      starterCode: `.badge {\n  /* pin to top-right of .card */\n}\n`,
      steps: [
        { label: "position is absolute", test: `getComputedStyle(document.querySelector('.badge')).position === 'absolute'` },
        { label: "top:8px right:8px", test: `const s=getComputedStyle(document.querySelector('.badge')); return s.top==='8px' && s.right==='8px';` },
      ],
      hints: [".badge{ position:absolute; top:8px; right:8px; }"],
      solution: `.badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n}`,
      quiz: [{ q: "absolute is relative to…", options: ["viewport always", "body always", "nearest positioned ancestor", "parent always"], answer: 2 }],
    },
    {
      id: "css-8",
      title: "Media Queries",
      emoji: "📱",
      difficulty: 3,
      language: "css",
      theory: "`@media (max-width: 600px)` applies styles only on narrow screens. The cornerstone of responsive design.",
      goal: "Make .box red by default, but turn it blue when the viewport is 600px or narrower.",
      previewHtml: `<div class="stage"><div class="box"></div></div>`,
      previewCss: `${SHELL_CSS}\n.box{width:120px;height:120px;border-radius:12px;}`,
      starterCode: `.box {\n  background: red;\n}\n\n@media (max-width: 600px) {\n  /* override here */\n}\n`,
      steps: [
        {
          label: "Has a max-width media query",
          test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(r.type===4 && /max-width/.test(r.conditionText||r.media.mediaText)) ok=true; } return ok;`,
        },
        {
          label: "Override sets blue",
          test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(r.type===4){ for(const sub of r.cssRules){ if(/\\.box/.test(sub.selectorText) && (sub.style.backgroundColor==='blue' || sub.style.background==='blue')) ok=true; } } } return ok;`,
        },
      ],
      hints: ["@media (max-width: 600px) { .box { background: blue; } }"],
      solution: `.box {\n  background: red;\n}\n@media (max-width: 600px) {\n  .box { background: blue; }\n}`,
      quiz: [{ q: "Mobile-first means starting with…", options: ["max-width", "min-width", "no media queries", "JS detection"], answer: 1 }],
    },
    {
      id: "css-9",
      title: "Gradients",
      emoji: "🌈",
      difficulty: 2,
      language: "css",
      theory: "`linear-gradient(angle, color1, color2)` paints a gradient as a background image. Angles: 0deg=up, 90deg=right.",
      goal: "Give .hero a 135deg linear-gradient from hotpink to gold.",
      previewHtml: `<div class="stage"><div class="hero">Hero</div></div>`,
      previewCss: `${SHELL_CSS}\n.hero{width:280px;height:140px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:700;color:#fff;}`,
      starterCode: `.hero {\n  /* linear-gradient 135deg, hotpink → gold */\n}\n`,
      steps: [
        {
          label: "Background uses a gradient",
          test: `const bg=getComputedStyle(document.querySelector('.hero')).backgroundImage; return /linear-gradient/.test(bg) && /135deg/.test(bg) && /255, 105, 180/.test(bg) && /255, 215, 0/.test(bg);`,
        },
      ],
      hints: ["background: linear-gradient(135deg, hotpink, gold);"],
      solution: `.hero {\n  background: linear-gradient(135deg, hotpink, gold);\n}`,
      quiz: [{ q: "Which is a CSS gradient function?", options: ["linear()", "linear-gradient()", "gradient()", "fade()"], answer: 1 }],
    },
  ],
};
