import type { Section } from "../types";

const SHELL_CSS = `
  body{margin:0;font-family:'JetBrains Mono',monospace;background:#0f0f17;color:#f5f5dc;padding:24px;}
  .stage{display:flex;align-items:center;justify-content:center;gap:14px;min-height:240px;}
`;

export const cssBasicsSection: Section = {
  id: "css-basics",
  title: "CSS Foundations",
  emoji: "🎨",
  blurb: "Selectors, the box model, color and units.",
  levels: [
    {
      id: "css-1",
      title: "Color the Box",
      emoji: "🟪",
      difficulty: 1,
      language: "css",
      theory: "Class selectors start with `.classname`. Use `background-color` and `color` to style.",
      goal: "Make .box have a hot pink background and white text.",
      previewHtml: `<div class="stage"><div class="box">Hello</div></div>`,
      previewCss: `${SHELL_CSS}\n.box{padding:30px 40px;border-radius:12px;font-size:24px;font-weight:700;}`,
      starterCode: `.box {\n  /* your styles */\n}\n`,
      steps: [
        { label: "Background is hot pink", test: `getComputedStyle(document.querySelector('.box')).backgroundColor === 'rgb(255, 105, 180)'` },
        { label: "Text is white", test: `getComputedStyle(document.querySelector('.box')).color === 'rgb(255, 255, 255)'` },
      ],
      hints: ["background: hotpink; color: white;"],
      solution: `.box {\n  background: hotpink;\n  color: white;\n}`,
      quiz: [{ q: "What's the class selector for .btn?", options: ["#btn", ".btn", "btn", "*btn"], answer: 1 }],
    },
    {
      id: "css-2",
      title: "Box Model",
      emoji: "📦",
      difficulty: 1,
      language: "css",
      theory: "Every element is a box: content + padding + border + margin. `box-sizing: border-box` makes width include padding & border.",
      goal: "Give .card 24px padding, a 4px solid gold border, and 16px border-radius.",
      previewHtml: `<div class="stage"><div class="card">Card</div></div>`,
      previewCss: `${SHELL_CSS}\n.card{background:#1a1a24;color:#facc15;font-weight:700;}`,
      starterCode: `.card {\n  /* padding, border, border-radius */\n}\n`,
      steps: [
        { label: "Padding 24px", test: `getComputedStyle(document.querySelector('.card')).paddingTop === '24px'` },
        { label: "4px solid gold border", test: `const s=getComputedStyle(document.querySelector('.card')); return s.borderTopWidth==='4px' && s.borderTopStyle==='solid' && s.borderTopColor==='rgb(255, 215, 0)';` },
        { label: "Border-radius 16px", test: `getComputedStyle(document.querySelector('.card')).borderTopLeftRadius === '16px'` },
      ],
      hints: ["padding:24px; border:4px solid gold; border-radius:16px;"],
      solution: `.card {\n  padding: 24px;\n  border: 4px solid gold;\n  border-radius: 16px;\n}`,
      quiz: [{ q: "Which is OUTSIDE the border?", options: ["padding", "margin", "content", "outline-width"], answer: 1 }],
    },
    {
      id: "css-3",
      title: "Hover State",
      emoji: "👆",
      difficulty: 2,
      language: "css",
      theory: "Pseudo-classes like `:hover` apply styles on user interaction. Combine with `transition` for smoothness.",
      goal: "On .btn:hover, make the background 'crimson'. Also add a 0.3s transition on background-color.",
      previewHtml: `<div class="stage"><button class="btn">Hover me</button></div>`,
      previewCss: `${SHELL_CSS}\n.btn{padding:14px 28px;border:0;border-radius:8px;background:#facc15;color:#111;font-size:18px;font-weight:700;cursor:pointer;}`,
      starterCode: `.btn {\n  transition: /* ... */;\n}\n\n.btn:hover {\n  /* ... */\n}\n`,
      steps: [
        { label: "transition includes background-color 0.3s", test: `const t=getComputedStyle(document.querySelector('.btn')).transition; return /background-color/.test(t) && /0\\.3s/.test(t);` },
        {
          label: "Hover background is crimson",
          test: `const sheet=document.getElementById('__user_css').sheet; let found=false; for (const r of sheet.cssRules){ if(r.selectorText && r.selectorText.includes(':hover') && r.style.backgroundColor && (r.style.backgroundColor==='crimson' || r.style.backgroundColor==='rgb(220, 20, 60)')) found=true; } return found;`,
          hint: "Add .btn:hover { background: crimson; }",
        },
      ],
      hints: [".btn{ transition: background-color .3s; }", ".btn:hover{ background: crimson; }"],
      solution: `.btn {\n  transition: background-color .3s;\n}\n.btn:hover {\n  background: crimson;\n}`,
      quiz: [{ q: ":hover is a…", options: ["pseudo-element", "pseudo-class", "media query", "selector list"], answer: 1 }],
    },
    {
      id: "css-4",
      title: "Specificity",
      emoji: "🎯",
      difficulty: 2,
      language: "css",
      theory: "Specificity ranking: inline > id (#) > class (.) > tag. The MORE specific selector wins when rules conflict.",
      goal: "Without changing the HTML, make the text inside #target turn 'limegreen'. There's already a generic rule fighting you — beat it!",
      previewHtml: `<div class="stage"><p id="target" class="text">Color me lime!</p></div>`,
      previewCss: `${SHELL_CSS}\n.text{color:gray;font-size:24px;font-weight:700;}`,
      starterCode: `/* Use a more specific selector */\n`,
      steps: [
        { label: "#target text is limegreen", test: `getComputedStyle(document.getElementById('target')).color === 'rgb(50, 205, 50)'` },
      ],
      hints: ["#target { color: limegreen; }"],
      solution: `#target { color: limegreen; }`,
      quiz: [{ q: "Highest natural specificity?", options: [".class", "tag", "#id", "*"], answer: 2 }],
    },
    {
      id: "css-5",
      title: "Pseudo-elements",
      emoji: "✨",
      difficulty: 2,
      language: "css",
      theory: "`::before` and `::after` insert generated content. They need a `content` property — even if empty ('').",
      goal: "Add a ⭐ before .badge using ::before. Give it 6px right margin.",
      previewHtml: `<div class="stage"><span class="badge">Pro</span></div>`,
      previewCss: `${SHELL_CSS}\n.badge{padding:6px 12px;border-radius:999px;background:#facc15;color:#111;font-weight:700;}`,
      starterCode: `.badge::before {\n  /* content + margin */\n}\n`,
      steps: [
        {
          label: "::before content is a star",
          test: `const cs=getComputedStyle(document.querySelector('.badge'),'::before'); return /★|⭐/.test(cs.content) || cs.content.includes('star');`,
        },
        {
          label: "::before has 6px right margin",
          test: `getComputedStyle(document.querySelector('.badge'),'::before').marginRight === '6px'`,
        },
      ],
      hints: [".badge::before{ content:'⭐'; margin-right:6px; }"],
      solution: `.badge::before {\n  content: '⭐';\n  margin-right: 6px;\n}`,
      quiz: [{ q: "Pseudo-elements need which property?", options: ["display", "content", "before", "src"], answer: 1 }],
    },
    {
      id: "css-6",
      title: "Variables (Custom Properties)",
      emoji: "🎨",
      difficulty: 2,
      language: "css",
      theory: "CSS variables: `--name: value` on a selector, `var(--name)` to use. They cascade and can be overridden per-component.",
      goal: "Define `--brand: #22d3ee` on `:root` and use it for .btn's background.",
      previewHtml: `<div class="stage"><button class="btn">Click</button></div>`,
      previewCss: `${SHELL_CSS}\n.btn{padding:12px 24px;border:0;border-radius:8px;font-weight:700;color:#111;font-size:18px;cursor:pointer;}`,
      starterCode: `:root {\n  /* --brand */\n}\n.btn {\n  /* use var() */\n}\n`,
      steps: [
        { label: "--brand defined as #22d3ee", test: `getComputedStyle(document.documentElement).getPropertyValue('--brand').trim().toLowerCase() === '#22d3ee'` },
        { label: "Button background uses var", test: `getComputedStyle(document.querySelector('.btn')).backgroundColor === 'rgb(34, 211, 238)'` },
      ],
      hints: [":root{ --brand: #22d3ee; }", ".btn{ background: var(--brand); }"],
      solution: `:root {\n  --brand: #22d3ee;\n}\n.btn {\n  background: var(--brand);\n}`,
      quiz: [{ q: "How do you READ a CSS var?", options: ["read()", "var()", "$()", "get()"], answer: 1 }],
    },
    {
      id: "css-7",
      title: "Position Absolute",
      emoji: "📍",
      difficulty: 2,
      language: "css",
      theory: "`position: absolute` removes from flow and positions relative to the nearest *positioned* ancestor (often `position: relative`).",
      goal: "Anchor the .badge to the top-right corner of .card (top: 8px; right: 8px).",
      previewHtml: `<div class="stage"><div class="card">Card<span class="badge">NEW</span></div></div>`,
      previewCss: `${SHELL_CSS}\n.card{position:relative;width:200px;height:120px;background:#1a1a24;color:#fff;padding:14px;border-radius:10px;}\n.badge{background:#ef4444;color:#fff;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:700;}`,
      starterCode: `.badge {\n  /* pin to top-right of .card */\n}\n`,
      steps: [
        { label: "position is absolute", test: `getComputedStyle(document.querySelector('.badge')).position === 'absolute'` },
        { label: "top:8px right:8px", test: `const s=getComputedStyle(document.querySelector('.badge')); return s.top==='8px' && s.right==='8px';` },
      ],
      hints: [".badge{ position:absolute; top:8px; right:8px; }"],
      solution: `.badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n}`,
      quiz: [{ q: "absolute is relative to…", options: ["viewport always", "body always", "nearest positioned ancestor", "parent always"], answer: 2 }],
    },
    {
      id: "css-8",
      title: "Media Queries",
      emoji: "📱",
      difficulty: 3,
      language: "css",
      theory: "`@media (max-width: 600px)` applies styles only on narrow screens. The cornerstone of responsive design.",
      goal: "Make .box red by default, but turn it blue when the viewport is 600px or narrower.",
      previewHtml: `<div class="stage"><div class="box"></div></div>`,
      previewCss: `${SHELL_CSS}\n.box{width:120px;height:120px;border-radius:12px;}`,
      starterCode: `.box {\n  background: red;\n}\n\n@media (max-width: 600px) {\n  /* override here */\n}\n`,
      steps: [
        {
          label: "Has a max-width media query",
          test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(r.type===4 && /max-width/.test(r.conditionText||r.media.mediaText)) ok=true; } return ok;`,
        },
        {
          label: "Override sets blue",
          test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(r.type===4){ for(const sub of r.cssRules){ if(/\\.box/.test(sub.selectorText) && (sub.style.backgroundColor==='blue' || sub.style.background==='blue')) ok=true; } } } return ok;`,
        },
      ],
      hints: ["@media (max-width: 600px) { .box { background: blue; } }"],
      solution: `.box {\n  background: red;\n}\n@media (max-width: 600px) {\n  .box { background: blue; }\n}`,
      quiz: [{ q: "Mobile-first means starting with…", options: ["max-width", "min-width", "no media queries", "JS detection"], answer: 1 }],
    },
    {
      id: "css-9",
      title: "Gradients",
      emoji: "🌈",
      difficulty: 2,
      language: "css",
      theory: "`linear-gradient(angle, color1, color2)` paints a gradient as a background image. Angles: 0deg=up, 90deg=right.",
      goal: "Give .hero a 135deg linear-gradient from hotpink to gold.",
      previewHtml: `<div class="stage"><div class="hero">Hero</div></div>`,
      previewCss: `${SHELL_CSS}\n.hero{width:280px;height:140px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:700;color:#fff;}`,
      starterCode: `.hero {\n  /* linear-gradient 135deg, hotpink → gold */\n}\n`,
      steps: [
        {
          label: "Background uses a gradient",
          test: `const bg=getComputedStyle(document.querySelector('.hero')).backgroundImage; return /linear-gradient/.test(bg) && /135deg/.test(bg) && /255, 105, 180/.test(bg) && /255, 215, 0/.test(bg);`,
        },
      ],
      hints: ["background: linear-gradient(135deg, hotpink, gold);"],
      solution: `.hero {\n  background: linear-gradient(135deg, hotpink, gold);\n}`,
      quiz: [{ q: "Which is a CSS gradient function?", options: ["linear()", "linear-gradient()", "gradient()", "fade()"], answer: 1 }],
    },
    {
      id: "css-10",
      title: "Opacity & Alpha",
      emoji: "👻",
      difficulty: 1,
      language: "css",
      theory: "`opacity: 0..1` fades the WHOLE element (including children). For color-only transparency use `rgba()` or `hsla()` — that won't fade text.",
      goal: "Set .ghost opacity to 0.4 and give .panel a background of rgba(34,211,238,0.25).",
      previewHtml: `<div class="stage"><div class="panel"><span class="ghost">Boo</span></div></div>`,
      previewCss: `${SHELL_CSS}\n.panel{padding:30px 40px;border-radius:12px;color:#fff;font-weight:700;font-size:24px;}\n.ghost{display:inline-block;}`,
      starterCode: `.ghost {\n  /* opacity */\n}\n.panel {\n  /* rgba background */\n}\n`,
      steps: [
        { label: ".ghost opacity is 0.4", test: `getComputedStyle(document.querySelector('.ghost')).opacity === '0.4'` },
        { label: ".panel background is rgba(34,211,238,0.25)", test: `getComputedStyle(document.querySelector('.panel')).backgroundColor === 'rgba(34, 211, 238, 0.25)'` },
      ],
      hints: [".ghost{opacity:.4} .panel{background:rgba(34,211,238,.25)}"],
      solution: `.ghost { opacity: 0.4; }\n.panel { background: rgba(34, 211, 238, 0.25); }`,
      quiz: [{ q: "Which fades children too?", options: ["rgba()", "opacity", "hsla()", "filter:hue-rotate"], answer: 1 }],
    },
    {
      id: "css-11",
      title: "Transitions",
      emoji: "🎞️",
      difficulty: 2,
      language: "css",
      theory: "`transition: <prop> <duration> <easing> <delay>`. Animates property changes smoothly. Use `all` cautiously — it's expensive.",
      goal: "Add a 0.5s ease-in-out transition on transform for .box, then on hover scale it to 1.2.",
      previewHtml: `<div class="stage"><div class="box">Hover</div></div>`,
      previewCss: `${SHELL_CSS}\n.box{width:120px;height:120px;background:#22d3ee;border-radius:12px;display:flex;align-items:center;justify-content:center;color:#111;font-weight:700;cursor:pointer;}`,
      starterCode: `.box {\n  /* transition */\n}\n.box:hover {\n  /* transform */\n}\n`,
      steps: [
        { label: "Transition on transform 0.5s ease-in-out", test: `const t=getComputedStyle(document.querySelector('.box')).transition; return /transform/.test(t) && /0\\.5s/.test(t) && /ease-in-out/.test(t);` },
        { label: ":hover scales to 1.2", test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(r.selectorText && r.selectorText.includes(':hover') && /scale\\(1\\.2\\)/.test(r.style.transform)) ok=true; } return ok;` },
      ],
      hints: [".box{transition: transform .5s ease-in-out;} .box:hover{transform:scale(1.2);}"],
      solution: `.box { transition: transform 0.5s ease-in-out; }\n.box:hover { transform: scale(1.2); }`,
      quiz: [{ q: "Order of transition shorthand?", options: ["delay duration prop", "prop duration easing delay", "easing prop duration", "duration prop easing"], answer: 1 }],
    },
    {
      id: "css-12",
      title: "Transformations",
      emoji: "🔄",
      difficulty: 2,
      language: "css",
      theory: "`transform` can `translate()`, `rotate()`, `scale()`, `skew()`. Combine in one declaration: `transform: rotate(15deg) scale(1.1);`. GPU-accelerated.",
      goal: "Rotate .card 10deg AND translateY -8px in a single transform.",
      previewHtml: `<div class="stage"><div class="card">忍</div></div>`,
      previewCss: `${SHELL_CSS}\n.card{width:120px;height:120px;background:linear-gradient(135deg,#22d3ee,#3b82f6);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:48px;color:#fff;}`,
      starterCode: `.card {\n  /* combined transform */\n}\n`,
      steps: [
        { label: "Has rotate(10deg) and translateY(-8px)", test: `const sheet=document.getElementById('__user_css').sheet; let ok=false; for(const r of sheet.cssRules){ if(/\\.card/.test(r.selectorText) && /rotate\\(10deg\\)/.test(r.style.transform) && /translateY\\(-8px\\)/.test(r.style.transform)) ok=true; } return ok;` },
      ],
      hints: ["transform: rotate(10deg) translateY(-8px);"],
      solution: `.card { transform: rotate(10deg) translateY(-8px); }`,
      quiz: [{ q: "Which is GPU-accelerated?", options: ["top/left", "margin", "transform", "width"], answer: 2 }],
    },
    {
      id: "css-13",
      title: "Pseudo-class :nth-child",
      emoji: "🔢",
      difficulty: 2,
      language: "css",
      theory: "`:nth-child(n)` matches by position. Use keywords (`odd`, `even`) or formulas (`2n+1`, `3n`). Great for striping tables/lists.",
      goal: "Color every EVEN <li> in .list with background #1e293b.",
      previewHtml: `<div class="stage"><ul class="list"><li>One</li><li>Two</li><li>Three</li><li>Four</li></ul></div>`,
      previewCss: `${SHELL_CSS}\n.list{list-style:none;padding:0;margin:0;}\n.list li{padding:10px 16px;color:#fff;}`,
      starterCode: `.list li:nth-child(/* ? */) {\n  /* background */\n}\n`,
      steps: [
        { label: "Even items have bg #1e293b", test: `getComputedStyle(document.querySelectorAll('.list li')[1]).backgroundColor === 'rgb(30, 41, 59)' && getComputedStyle(document.querySelectorAll('.list li')[0]).backgroundColor !== 'rgb(30, 41, 59)'` },
      ],
      hints: [".list li:nth-child(even){ background:#1e293b; }"],
      solution: `.list li:nth-child(even) { background: #1e293b; }`,
      quiz: [{ q: "Which selects items 2,4,6…?", options: [":nth-child(odd)", ":nth-child(2n)", ":nth-child(n+2)", ":first-child"], answer: 1 }],
    },
    {
      id: "css-14",
      title: "Pseudo-element ::first-letter",
      emoji: "🅰️",
      difficulty: 2,
      language: "css",
      theory: "`::first-letter` styles only the first letter of a block — perfect for drop caps. `::selection` styles highlighted text.",
      goal: "Make the first letter of .article 48px and color #22d3ee.",
      previewHtml: `<div class="stage"><p class="article">Vanilla Ninja teaches you the web.</p></div>`,
      previewCss: `${SHELL_CSS}\n.article{max-width:300px;color:#fff;font-size:18px;line-height:1.5;}`,
      starterCode: `.article::first-letter {\n  /* size + color */\n}\n`,
      steps: [
        { label: "::first-letter is 48px cyan", test: `const cs=getComputedStyle(document.querySelector('.article'),'::first-letter'); return cs.fontSize==='48px' && cs.color==='rgb(34, 211, 238)';` },
      ],
      hints: [".article::first-letter{ font-size:48px; color:#22d3ee; }"],
      solution: `.article::first-letter { font-size: 48px; color: #22d3ee; }`,
      quiz: [{ q: "How many colons for pseudo-elements (modern)?", options: ["one", "two", "three", "none"], answer: 1 }],
    },
    {
      id: "css-15",
      title: "Attribute Selectors",
      emoji: "🏷️",
      difficulty: 2,
      language: "css",
      theory: "Select by attribute: `[type='email']`, `[href^='https']` (starts with), `[href$='.pdf']` (ends with), `[class*='btn']` (contains).",
      goal: "Style every <a> whose href starts with 'https' — make it color #22d3ee and bold.",
      previewHtml: `<div class="stage"><p><a href="https://lovable.dev">secure</a> · <a href="http://old.com">insecure</a></p></div>`,
      previewCss: `${SHELL_CSS}\na{color:#94a3b8;margin:0 6px;}`,
      starterCode: `a[/* attribute selector */] {\n  /* color + weight */\n}\n`,
      steps: [
        { label: "https link is cyan & bold", test: `const a=document.querySelector('a[href^="https"]'); const s=getComputedStyle(a); return s.color==='rgb(34, 211, 238)' && (s.fontWeight==='700' || s.fontWeight==='bold');` },
        { label: "http link is NOT cyan", test: `getComputedStyle(document.querySelector('a[href^="http:"]')).color !== 'rgb(34, 211, 238)'` },
      ],
      hints: [`a[href^="https"]{ color:#22d3ee; font-weight:bold; }`],
      solution: `a[href^="https"] {\n  color: #22d3ee;\n  font-weight: bold;\n}`,
      quiz: [{ q: "[href$='.pdf'] means…", options: ["contains .pdf", "starts with .pdf", "ends with .pdf", "equals .pdf"], answer: 2 }],
    },
    {
      id: "css-16",
      title: "Z-index & Stacking",
      emoji: "🃏",
      difficulty: 2,
      language: "css",
      theory: "`z-index` only works on positioned elements (not `static`). Higher z-index = on top. Each positioned ancestor creates a new stacking context.",
      goal: "Make .top sit ABOVE .bottom by giving it position:relative and z-index:10.",
      previewHtml: `<div class="stage"><div class="bottom">Bottom</div><div class="top">Top</div></div>`,
      previewCss: `${SHELL_CSS}\n.bottom,.top{width:120px;height:120px;border-radius:12px;display:flex;align-items:center;justify-content:center;color:#111;font-weight:700;}\n.bottom{background:#facc15;}\n.top{background:#22d3ee;margin-left:-60px;}`,
      starterCode: `.top {\n  /* position + z-index */\n}\n`,
      steps: [
        { label: ".top is positioned relative", test: `getComputedStyle(document.querySelector('.top')).position === 'relative'` },
        { label: ".top z-index is 10", test: `getComputedStyle(document.querySelector('.top')).zIndex === '10'` },
      ],
      hints: [".top{ position:relative; z-index:10; }"],
      solution: `.top {\n  position: relative;\n  z-index: 10;\n}`,
      quiz: [{ q: "z-index needs which?", options: ["display:block", "a position other than static", "float", "nothing"], answer: 1 }],
    },
    {
      id: "css-17",
      title: "calc() & var()",
      emoji: "🧮",
      difficulty: 3,
      language: "css",
      theory: "`calc()` mixes units: `calc(100% - 40px)`. Combine with `var()` for dynamic, themable layouts: `calc(var(--gap) * 2)`.",
      goal: "Define `--gap: 16px` on :root, then make .panel width = `calc(100% - var(--gap) * 4)` and padding = `var(--gap)`.",
      previewHtml: `<div class="stage" style="width:400px;"><div class="panel">Fluid</div></div>`,
      previewCss: `${SHELL_CSS}\n.panel{background:#1e293b;color:#22d3ee;border-radius:12px;font-weight:700;text-align:center;}`,
      starterCode: `:root {\n  /* --gap */\n}\n.panel {\n  /* width with calc + var, padding with var */\n}\n`,
      steps: [
        { label: "--gap is 16px", test: `getComputedStyle(document.documentElement).getPropertyValue('--gap').trim() === '16px'` },
        { label: "Padding equals 16px", test: `getComputedStyle(document.querySelector('.panel')).paddingTop === '16px'` },
        { label: "Width = stage width - 64px (336px)", test: `getComputedStyle(document.querySelector('.panel')).width === '336px'` },
      ],
      hints: [":root{--gap:16px}", ".panel{ width: calc(100% - var(--gap) * 4); padding: var(--gap); }"],
      solution: `:root { --gap: 16px; }\n.panel {\n  width: calc(100% - var(--gap) * 4);\n  padding: var(--gap);\n}`,
      quiz: [{ q: "Which is valid?", options: ["calc(100%-40px)", "calc(100% - 40px)", "calc[100% - 40px]", "calc:100%-40px"], answer: 1 }],
    },
  ],
};
