import type { Section } from "../types";

export const dataStructuresSection: Section = {
  id: "data-structures",
  title: "Data Structures",
  emoji: "🧠",
  blurb: "Map, Set, WeakMap, stacks & queues — pick the right tool.",
  levels: [
    {
      id: "ds-1",
      title: "Set: Unique Items",
      emoji: "🎯",
      difficulty: 1,
      theory: "`Set` stores unique values. Great for de-duplication.",
      goal: "From `nums = [1,2,2,3,3,3,4]`, build `unique` = array of unique values.",
      starterCode: `const nums = [1,2,2,3,3,3,4];\n// const unique = ...\n`,
      steps: [
        { label: "unique is [1,2,3,4]", test: `JSON.stringify(unique) === '[1,2,3,4]'` },
      ],
      hints: ["[...new Set(nums)]"],
      solution: `const nums=[1,2,2,3,3,3,4]; const unique = [...new Set(nums)];`,
      quiz: [{ q: "Set membership check uses…", options: ["==", "===", "SameValueZero", "Object.is exactly"], answer: 2 }],
    },
    {
      id: "ds-2",
      title: "Map: Keyed Values",
      emoji: "🗺️",
      difficulty: 2,
      theory: "Unlike plain objects, `Map` keys can be ANY value (objects, functions). Preserves insertion order.",
      goal: "Build `m = new Map()`. Set 'a'→1, 'b'→2. Compute `total` = sum of all values.",
      starterCode: `const m = new Map();\n// set entries\n// const total = ...\n`,
      steps: [
        { label: "m.size === 2", test: `m.size === 2` },
        { label: "total === 3", test: `total === 3` },
      ],
      hints: ["[...m.values()].reduce((a,b)=>a+b, 0)"],
      solution: `const m=new Map(); m.set('a',1); m.set('b',2); const total = [...m.values()].reduce((a,b)=>a+b,0);`,
      quiz: [{ q: "Map vs Object: a key advantage of Map is…", options: ["JSON serialization", "any key type & ordered", "smaller memory", "faster always"], answer: 1 }],
    },
    {
      id: "ds-3",
      title: "Stack via Array",
      emoji: "🥞",
      difficulty: 2,
      theory: "A stack is LIFO. Use `push` to add, `pop` to remove.",
      goal: "Build class `Stack` with push(x), pop(), peek(), size().",
      starterCode: `class Stack {\n  // implement\n}\n`,
      steps: [
        { label: "push then peek", test: `(()=>{ const s=new Stack(); s.push(1); s.push(2); return s.peek()===2 && s.size()===2; })()` },
        { label: "pop returns top", test: `(()=>{ const s=new Stack(); s.push('a'); s.push('b'); return s.pop()==='b' && s.peek()==='a'; })()` },
      ],
      hints: ["Use a private array and delegate."],
      solution: `class Stack{ constructor(){ this._a=[]; } push(x){ this._a.push(x); } pop(){ return this._a.pop(); } peek(){ return this._a[this._a.length-1]; } size(){ return this._a.length; } }`,
      quiz: [{ q: "LIFO means…", options: ["First in, first out", "Last in, first out", "Random", "Sorted"], answer: 1 }],
    },
    {
      id: "ds-4",
      title: "Queue via Two Stacks",
      emoji: "🚶",
      difficulty: 3,
      theory: "FIFO behavior using two LIFO stacks — classic interview question.",
      goal: "Class `Queue` with enqueue(x), dequeue(). Use two internal arrays. Order must be FIFO.",
      starterCode: `class Queue {\n  // two-stack implementation\n}\n`,
      steps: [
        { label: "FIFO order", test: `(()=>{ const q=new Queue(); q.enqueue(1); q.enqueue(2); q.enqueue(3); return q.dequeue()===1 && q.dequeue()===2 && q.dequeue()===3; })()` },
      ],
      hints: ["On dequeue: if out is empty, drain in into out by popping."],
      solution: `class Queue{ constructor(){ this.in=[]; this.out=[]; } enqueue(x){ this.in.push(x); } dequeue(){ if(!this.out.length){ while(this.in.length) this.out.push(this.in.pop()); } return this.out.pop(); } }`,
      quiz: [{ q: "Amortized cost per op for two-stack queue?", options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], answer: 2 }],
    },
    {
      id: "ds-5",
      title: "WeakMap for Private Data",
      emoji: "🪶",
      difficulty: 3,
      theory: "`WeakMap` keys must be objects and are weakly held — entries vanish when key is GC'd. Great for hidden per-instance data.",
      goal: "Use a WeakMap `_secret` to store a private number per object. Function `setSecret(obj, n)` and `getSecret(obj)`.",
      starterCode: `const _secret = new WeakMap();\n// function setSecret(obj, n)\n// function getSecret(obj)\n`,
      steps: [
        { label: "Round-trip works", test: `(()=>{ const o={}; setSecret(o, 42); return getSecret(o) === 42; })()` },
        { label: "Different objects, different secrets", test: `(()=>{ const a={}, b={}; setSecret(a,1); setSecret(b,2); return getSecret(a)===1 && getSecret(b)===2; })()` },
      ],
      hints: ["_secret.set(obj, n); _secret.get(obj);"],
      solution: `const _secret=new WeakMap(); function setSecret(o,n){ _secret.set(o,n); } function getSecret(o){ return _secret.get(o); }`,
      quiz: [{ q: "WeakMap keys must be…", options: ["strings", "objects", "numbers", "anything"], answer: 1 }],
    },
  ],
};
