import type { Section } from "../types";
import { STAGE_CSS } from "../shared";

export const domAdvancedSection: Section = {
  id: "dom-advanced",
  title: "DOM & Events Pro",
  emoji: "🖱️",
  blurb: "Delegation, forms, drag, intersection, storage.",
  levels: [
    {
      id: "doma-1",
      title: "Event Delegation",
      emoji: "🎯",
      difficulty: 2,
      theory: "Attach ONE listener on a parent and inspect `event.target` to handle many children efficiently.",
      goal: "On click of any <li> inside #list, set window.lastClicked to that li's text. Use a SINGLE listener on #list.",
      previewHtml: `<div class="stage"><ul id="list" class="list"><li>apple</li><li>banana</li><li>cherry</li></ul></div>`,
      previewCss: `${STAGE_CSS}\n.list{font-size:22px;list-style:square;color:#facc15;cursor:pointer;}`,
      starterCode: `const list = document.getElementById('list');\n// add ONE listener on #list\n`,
      steps: [
        {
          label: "Clicking 'banana' sets window.lastClicked",
          test: `const lis = document.querySelectorAll('#list li'); lis[1].click(); return window.lastClicked === 'banana';`,
          hint: "Inside handler: if(e.target.tagName==='LI') window.lastClicked = e.target.textContent;",
        },
      ],
      hints: ["list.addEventListener('click', e => { if(e.target.tagName==='LI') window.lastClicked = e.target.textContent; });"],
      solution: `document.getElementById('list').addEventListener('click', e => { if(e.target.tagName==='LI') window.lastClicked = e.target.textContent; });`,
      quiz: [{ q: "Delegation reduces…", options: ["accuracy", "number of listeners", "event order", "DOM size"], answer: 1 }],
    },
    {
      id: "doma-2",
      title: "Form Submit + preventDefault",
      emoji: "📝",
      difficulty: 2,
      theory: "Prevent default form submission with `e.preventDefault()` to handle data in JS.",
      goal: "On submit of #f, prevent reload and store input value in window.submitted.",
      previewHtml: `<form id="f" class="stage"><input id="i" value="hello"/><button type="submit">Go</button></form>`,
      previewCss: `${STAGE_CSS}\ninput{padding:8px;border-radius:6px;border:1px solid #444;background:#222;color:#fff;}\nbutton{padding:8px 12px;margin-left:8px;border-radius:6px;background:#facc15;color:#111;border:0;cursor:pointer;}`,
      starterCode: `const f = document.getElementById('f');\n// add a submit listener\n`,
      steps: [
        {
          label: "submit captures input value",
          test: `f.requestSubmit ? f.requestSubmit() : f.dispatchEvent(new Event('submit', {cancelable:true})); await new Promise(r=>setTimeout(r,30)); return window.submitted === 'hello';`,
        },
      ],
      hints: ["f.addEventListener('submit', e=>{ e.preventDefault(); window.submitted = document.getElementById('i').value; });"],
      solution: `document.getElementById('f').addEventListener('submit', e=>{ e.preventDefault(); window.submitted = document.getElementById('i').value; });`,
      quiz: [{ q: "preventDefault stops…", options: ["bubbling", "the default browser action", "all listeners", "the event"], answer: 1 }],
    },
    {
      id: "doma-3",
      title: "Keyboard Input",
      emoji: "⌨️",
      difficulty: 2,
      theory: "`keydown` fires on every key. `event.key` is the readable key name ('Enter', 'a', 'ArrowUp').",
      goal: "On window keydown, append event.key into array window.keys (declare it). Test will dispatch 'a'.",
      starterCode: `window.keys = [];\n// add a keydown listener pushing event.key\n`,
      steps: [
        {
          label: "Captures dispatched key 'a'",
          test: `window.dispatchEvent(new KeyboardEvent('keydown', {key:'a'})); return window.keys[window.keys.length-1] === 'a';`,
        },
      ],
      hints: ["window.addEventListener('keydown', e => window.keys.push(e.key));"],
      solution: `window.keys=[]; window.addEventListener('keydown', e => window.keys.push(e.key));`,
      quiz: [{ q: "Which property gives the printable key?", options: ["keyCode", "key", "code", "which"], answer: 1 }],
    },
    {
      id: "doma-4",
      title: "localStorage",
      emoji: "💾",
      difficulty: 1,
      theory: "`localStorage.setItem(k,v)` saves a string per origin. `getItem` reads. JSON.stringify for objects.",
      goal: "Save object `{theme:'dark'}` under key 'prefs'. Read it back and parse into `prefs`.",
      starterCode: `// localStorage.setItem(...)\n// const prefs = JSON.parse(...)\n`,
      steps: [
        { label: "prefs.theme === 'dark'", test: `prefs && prefs.theme === 'dark'` },
        { label: "localStorage has key 'prefs'", test: `localStorage.getItem('prefs') !== null` },
      ],
      hints: ["localStorage.setItem('prefs', JSON.stringify({theme:'dark'}));"],
      solution: `localStorage.setItem('prefs', JSON.stringify({theme:'dark'}));\nconst prefs = JSON.parse(localStorage.getItem('prefs'));`,
      quiz: [{ q: "localStorage stores values as…", options: ["any type", "strings only", "JSON only", "buffers"], answer: 1 }],
    {
      id: "doma-5",
      title: "Drag & Drop",
      emoji: "🖐️",
      difficulty: 3,
      theory: "Native drag&drop fires `dragstart`, `dragover`, `drop`. Call `e.preventDefault()` on `dragover` to allow a drop.",
      goal: "Drag #pkg into #zone. On drop, append #pkg into #zone. Test simulates the events.",
      previewHtml: `<div class="stage" style="gap:24px"><div id="pkg" draggable="true" class="pkg">📦</div><div id="zone" class="zone">drop here</div></div>`,
      previewCss: `${STAGE_CSS}\n.pkg{font-size:48px;cursor:grab;user-select:none;}\n.zone{min-width:160px;min-height:80px;border:2px dashed #22d3ee;border-radius:12px;display:flex;align-items:center;justify-content:center;color:#94a3b8;}`,
      starterCode: `const pkg = document.getElementById('pkg');\nconst zone = document.getElementById('zone');\n// 1) zone needs dragover with preventDefault\n// 2) zone drop should appendChild(pkg)\n`,
      steps: [
        {
          label: "Drop moves #pkg into #zone",
          test: `const z=document.getElementById('zone'); const p=document.getElementById('pkg'); z.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true})); z.dispatchEvent(new DragEvent('drop',{bubbles:true})); return p.parentElement === z;`,
          hint: "zone.addEventListener('dragover', e => e.preventDefault()); zone.addEventListener('drop', () => zone.appendChild(pkg));",
        },
      ],
      hints: ["Without preventDefault on dragover the drop event never fires."],
      solution: `const pkg=document.getElementById('pkg');const zone=document.getElementById('zone');\nzone.addEventListener('dragover', e => e.preventDefault());\nzone.addEventListener('drop', () => zone.appendChild(pkg));`,
      quiz: [{ q: "Why call preventDefault on dragover?", options: ["to stop drag", "to allow drop", "to bubble", "to copy data"], answer: 1 }],
    },
    {
      id: "doma-6",
      title: "IntersectionObserver",
      emoji: "👁️",
      difficulty: 3,
      theory: "`IntersectionObserver` reports when a target enters/leaves the viewport — perfect for lazy-loading and scroll reveals.",
      goal: "Observe #target. When it intersects, set window.seen = true.",
      previewHtml: `<div class="stage"><div id="target" class="target">watch me</div></div>`,
      previewCss: `${STAGE_CSS}\n.target{padding:24px 36px;background:#1e293b;border-radius:12px;color:#22d3ee;font-weight:700;}`,
      starterCode: `window.seen = false;\nconst target = document.getElementById('target');\n// create an IntersectionObserver and observe target\n`,
      steps: [
        {
          label: "Observer fires and sets window.seen",
          test: `const t=document.getElementById('target'); await new Promise(r=>setTimeout(r,120)); return window.seen === true;`,
          hint: "new IntersectionObserver(es => { if(es.some(e=>e.isIntersecting)) window.seen = true; }).observe(target);",
        },
      ],
      hints: ["The callback receives an array of IntersectionObserverEntry objects."],
      solution: `window.seen=false;const target=document.getElementById('target');new IntersectionObserver(es=>{ if(es.some(e=>e.isIntersecting)) window.seen=true; }).observe(target);`,
      quiz: [{ q: "Which property tells if a target is visible?", options: ["isVisible", "isIntersecting", "inView", "shown"], answer: 1 }],
    },
    {
      id: "doma-7",
      title: "Custom Events",
      emoji: "📣",
      difficulty: 2,
      theory: "Dispatch your own events with `new CustomEvent(name, { detail })` and listen with `addEventListener` — great for decoupled components.",
      goal: "Listen for 'ninja:level-up' on window and store event.detail.level into window.lastLevel.",
      starterCode: `window.lastLevel = 0;\n// add listener for 'ninja:level-up' that stores e.detail.level\n`,
      steps: [
        {
          label: "Receives detail.level = 5",
          test: `window.dispatchEvent(new CustomEvent('ninja:level-up',{detail:{level:5}})); return window.lastLevel === 5;`,
          hint: "window.addEventListener('ninja:level-up', e => window.lastLevel = e.detail.level);",
        },
      ],
      hints: ["Custom event payload lives on `event.detail`."],
      solution: `window.lastLevel=0;window.addEventListener('ninja:level-up', e => window.lastLevel = e.detail.level);`,
      quiz: [{ q: "Where is custom event data stored?", options: ["e.data", "e.detail", "e.payload", "e.value"], answer: 1 }],
    },
    {
      id: "doma-8",
      title: "Debounce Input",
      emoji: "⏱️",
      difficulty: 3,
      theory: "Debouncing waits for a pause in events before firing — perfect for search inputs. Use `setTimeout` and clear the previous timer.",
      goal: "Wire #q's `input` event so window.searchValue updates only ~150ms AFTER the user stops typing.",
      previewHtml: `<div class="stage"><input id="q" placeholder="search…" /></div>`,
      previewCss: `${STAGE_CSS}\ninput{padding:10px 14px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#e2e8f0;font-size:16px;min-width:240px;}`,
      starterCode: `const q = document.getElementById('q');\nwindow.searchValue = '';\n// debounce input → window.searchValue\n`,
      steps: [
        {
          label: "Updates after pause, not immediately",
          test: `const q=document.getElementById('q'); q.value='hi'; q.dispatchEvent(new Event('input')); const immediate = window.searchValue; await new Promise(r=>setTimeout(r,250)); return immediate === '' && window.searchValue === 'hi';`,
          hint: "let t; q.addEventListener('input', () => { clearTimeout(t); t = setTimeout(() => window.searchValue = q.value, 150); });",
        },
      ],
      hints: ["Store the timer id in an outer variable so each new event clears the previous one."],
      solution: `const q=document.getElementById('q');window.searchValue='';let t;q.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>window.searchValue=q.value,150);});`,
      quiz: [{ q: "Debounce vs throttle: debounce fires…", options: ["at fixed intervals", "after activity stops", "on every event", "only once ever"], answer: 1 }],
    },
  ],
};
