import type { Section } from "../types";

export const errorsSection: Section = {
  id: "errors",
  title: "Error Handling",
  emoji: "🧯",
  blurb: "throw, try/catch, custom errors, async errors.",
  levels: [
    {
      id: "err-1",
      title: "throw & catch",
      emoji: "🎣",
      difficulty: 1,
      theory: "`throw new Error('msg')` raises an error. Wrap risky code in `try { } catch (e) { }`.",
      goal: "Function `safeDivide(a,b)` returns a/b but throws Error('div by zero') if b is 0. Wrap a call to safeDivide(1,0) and store caught message in `caught`.",
      starterCode: `function safeDivide(a,b){\n  // throw if b === 0\n}\nlet caught;\n// try { safeDivide(1,0); } catch(e){ caught = e.message; }\n`,
      steps: [
        { label: "safeDivide(10,2) === 5", test: `safeDivide(10,2) === 5` },
        { label: "caught === 'div by zero'", test: `caught === 'div by zero'` },
      ],
      hints: ["if(b===0) throw new Error('div by zero');"],
      solution: `function safeDivide(a,b){ if(b===0) throw new Error('div by zero'); return a/b; }\nlet caught; try { safeDivide(1,0); } catch(e){ caught = e.message; }`,
      quiz: [{ q: "Which clause ALWAYS runs?", options: ["try", "catch", "finally", "throw"], answer: 2 }],
    },
    {
      id: "err-2",
      title: "Custom Error Class",
      emoji: "🏷️",
      difficulty: 2,
      theory: "Extend `Error` to create domain-specific errors. Set `name` for distinguishability.",
      goal: "Define `class ValidationError extends Error` with name='ValidationError'. Throw + catch one; store the caught instance in `caught`.",
      starterCode: `class ValidationError /* extends Error */ {\n}\nlet caught;\n// try { throw new ValidationError('bad'); } catch(e){ caught = e; }\n`,
      steps: [
        { label: "caught instanceof ValidationError", test: `caught instanceof ValidationError` },
        { label: "caught instanceof Error", test: `caught instanceof Error` },
        { label: "caught.name === 'ValidationError'", test: `caught.name === 'ValidationError'` },
      ],
      hints: ["constructor(m){ super(m); this.name='ValidationError'; }"],
      solution: `class ValidationError extends Error{ constructor(m){ super(m); this.name='ValidationError'; } }\nlet caught; try { throw new ValidationError('bad'); } catch(e){ caught=e; }`,
      quiz: [{ q: "Why subclass Error?", options: ["faster throws", "stack traces & instanceof checks", "to disable catch", "for syntax"], answer: 1 }],
    },
    {
      id: "err-3",
      title: "Async Errors with try/await",
      emoji: "⚡",
      difficulty: 2,
      theory: "Inside async functions, `await` rejections become exceptions catchable with try/catch.",
      goal: "Async fn `safe()` awaits Promise.reject('boom') inside try/catch and returns the caught reason. Store result in `result`.",
      starterCode: `async function safe(){\n  // try/catch around await Promise.reject('boom')\n}\nconst result = await safe();\n`,
      steps: [
        { label: "result === 'boom'", test: `result === 'boom'` },
      ],
      hints: ["try { await Promise.reject('boom'); } catch(e){ return e; }"],
      solution: `async function safe(){ try { await Promise.reject('boom'); } catch(e){ return e; } }\nconst result = await safe();`,
      quiz: [{ q: "Unhandled promise rejections cause…", options: ["silent failure forever", "an unhandledrejection event", "a crash always", "a syntax error"], answer: 1 }],
    },
    {
      id: "err-4",
      title: "finally Cleanup",
      emoji: "🧹",
      difficulty: 2,
      theory: "`finally` runs whether or not an error was thrown — perfect for cleanup (closing files, hiding spinners).",
      goal: "Run a try that throws; in finally, set window.cleaned = true. Catch the error and store its message in `msg`.",
      starterCode: `let msg;\nwindow.cleaned = false;\n// try { throw new Error('x'); } catch(e){ msg = e.message; } finally { window.cleaned = true; }\n`,
      steps: [
        { label: "msg === 'x'", test: `msg === 'x'` },
        { label: "window.cleaned === true", test: `window.cleaned === true` },
      ],
      hints: ["Add a finally block."],
      solution: `let msg; window.cleaned=false; try { throw new Error('x'); } catch(e){ msg=e.message; } finally { window.cleaned=true; }`,
      quiz: [{ q: "If try returns, finally still…", options: ["skipped", "runs", "throws", "rewinds the return"], answer: 1 }],
    },
  ],
};
