import type { Section } from "../types";
import { STAGE_CSS, STAGE_HTML } from "../shared";

export const functionsSection: Section = {
  id: "functions",
  title: "Functions",
  emoji: "🧩",
  blurb: "Declarations, arrows, scope, recursion.",
  levels: [
    {
      id: "fn-1",
      title: "First Function",
      emoji: "🎯",
      difficulty: 1,
      theory: "Functions are reusable blocks. Declare with `function name(){}` or arrow `const name = () => {}`.",
      goal: "Write `square(n)` returning n*n.",
      starterCode: `function square(n){\n  // return n*n\n}\n`,
      steps: [
        { label: "square(4) === 16", test: `square(4) === 16` },
        { label: "square(0) === 0", test: `square(0) === 0` },
        { label: "square(-3) === 9", test: `square(-3) === 9` },
      ],
      hints: ["Use return n*n;"],
      solution: `function square(n){ return n*n; }`,
      quiz: [
        { q: "Arrow functions DO NOT have their own…", options: ["return value", "this", "parameters", "name"], answer: 1 },
      ],
    },
    {
      id: "fn-2",
      title: "Default & Rest Params",
      emoji: "🧰",
      difficulty: 2,
      theory: "Default values: `function f(x=1)`. Rest collects extras: `function f(...nums)`.",
      goal: "Write `sum(...nums)` returning the sum (0 when empty).",
      starterCode: `function sum(...nums){\n  // reduce nums\n}\n`,
      steps: [
        { label: "sum() === 0", test: `sum() === 0` },
        { label: "sum(1,2,3) === 6", test: `sum(1,2,3) === 6` },
        { label: "sum(10,-5,5) === 10", test: `sum(10,-5,5) === 10` },
      ],
      hints: ["return nums.reduce((a,b)=>a+b, 0);"],
      solution: `function sum(...nums){ return nums.reduce((a,b)=>a+b,0); }`,
      quiz: [{ q: "Rest must be the…", options: ["first param", "last param", "anywhere", "named 'rest'"], answer: 1 }],
    },
    {
      id: "fn-3",
      title: "Recursion: Factorial",
      emoji: "🌀",
      difficulty: 2,
      theory: "A recursive function calls itself. Always include a base case.",
      goal: "Write `fact(n)` using recursion. fact(0) === 1.",
      starterCode: `function fact(n){\n  // base + recursive case\n}\n`,
      steps: [
        { label: "fact(0) === 1", test: `fact(0) === 1` },
        { label: "fact(5) === 120", test: `fact(5) === 120` },
        { label: "fact(7) === 5040", test: `fact(7) === 5040` },
      ],
      hints: ["return n <= 1 ? 1 : n * fact(n-1);"],
      solution: `function fact(n){ return n<=1 ? 1 : n*fact(n-1); }`,
      quiz: [{ q: "Missing base case causes…", options: ["TypeError", "stack overflow", "undefined", "0"], answer: 1 }],
    },
    {
      id: "fn-4",
      title: "Closures: Counter",
      emoji: "🔐",
      difficulty: 3,
      theory: "A closure remembers variables from its outer scope. Classic use: private state.",
      goal: "Write `makeCounter()` that returns a function. Each call increments and returns the count starting at 1.",
      starterCode: `function makeCounter(){\n  // return a function\n}\n`,
      steps: [
        { label: "First call returns 1", test: `(()=>{ const c=makeCounter(); return c()===1; })()` },
        { label: "Increments independently", test: `(()=>{ const a=makeCounter(); const b=makeCounter(); a(); a(); return a()===3 && b()===1; })()` },
      ],
      hints: ["let n=0; return () => ++n;"],
      solution: `function makeCounter(){ let n=0; return ()=> ++n; }`,
      quiz: [{ q: "Closures capture variables by…", options: ["value at call time", "reference (live)", "deep clone", "JSON"], answer: 1 }],
    },
    {
      id: "fn-5",
      title: "Higher-Order: once()",
      emoji: "1️⃣",
      difficulty: 3,
      theory: "Higher-order functions take or return functions. `once(fn)` ensures fn runs only the first time.",
      goal: "Build `once(fn)` returning a wrapper. After the first call, subsequent calls return the FIRST result without invoking fn again.",
      starterCode: `function once(fn){\n  // return wrapped\n}\n`,
      steps: [
        { label: "Calls fn only once", test: `(()=>{ let n=0; const w=once(()=>++n); w(); w(); w(); return n===1; })()` },
        { label: "Returns memoized first result", test: `(()=>{ let n=0; const w=once(()=>++n); return w()===1 && w()===1 && w()===1; })()` },
      ],
      hints: ["let called=false, result; return (...a)=>{ if(!called){ called=true; result=fn(...a); } return result; };"],
      solution: `function once(fn){ let c=false, r; return (...a)=>{ if(!c){ c=true; r=fn(...a); } return r; }; }`,
      quiz: [{ q: "Higher-order functions…", options: ["are slower", "take/return functions", "must be async", "are deprecated"], answer: 1 }],
    },
    {
      id: "fn-6",
      title: "Currying",
      emoji: "🍛",
      difficulty: 3,
      theory: "Currying transforms `f(a,b,c)` into `f(a)(b)(c)`. Useful for partial application.",
      goal: "Write `add` such that `add(1)(2)(3) === 6`.",
      starterCode: `// const add = a => b => c => ...\n`,
      steps: [
        { label: "add(1)(2)(3) === 6", test: `add(1)(2)(3) === 6` },
        { label: "add(10)(20)(30) === 60", test: `add(10)(20)(30) === 60` },
      ],
      hints: ["const add = a => b => c => a+b+c;"],
      solution: `const add = a => b => c => a+b+c;`,
      quiz: [{ q: "Currying enables…", options: ["faster code", "partial application", "concurrency", "type safety"], answer: 1 }],
    },
    {
      id: "fn-7",
      title: "Memoization",
      emoji: "🧠",
      difficulty: 3,
      theory: "Cache function results by argument to avoid recomputation. Trade memory for speed.",
      goal: "Build `memoize(fn)` for a single argument. Repeated calls with the same arg return the cached value WITHOUT re-running fn.",
      starterCode: `function memoize(fn){\n  // return wrapped\n}\n`,
      steps: [
        { label: "Caches by argument", test: `(()=>{ let calls=0; const slow=x=>{ calls++; return x*2; }; const m=memoize(slow); m(3); m(3); m(3); return calls===1; })()` },
        { label: "Different args → fn runs again", test: `(()=>{ let calls=0; const slow=x=>{ calls++; return x; }; const m=memoize(slow); m(1); m(2); m(1); return calls===2; })()` },
      ],
      hints: ["const cache = new Map(); return (x) => { if(!cache.has(x)) cache.set(x, fn(x)); return cache.get(x); };"],
      solution: `function memoize(fn){ const c=new Map(); return x => { if(!c.has(x)) c.set(x, fn(x)); return c.get(x); }; }`,
      quiz: [{ q: "Memoization is unsafe for…", options: ["pure functions", "impure functions w/ side effects", "math", "strings"], answer: 1 }],
    },
  ],
};
