import type { Section } from "../types";

const SHELL_CSS = `
  body{margin:0;font-family:'JetBrains Mono',monospace;background:#0f0f17;color:#f5f5dc;padding:20px;line-height:1.5;}
  h1,h2,h3{color:#facc15;margin:.4em 0;}
  a{color:#22d3ee;}
  ul,ol{padding-left:22px;}
  img{max-width:100%;border-radius:8px;}
  form{display:flex;flex-direction:column;gap:8px;max-width:300px;}
  input,button,textarea,select{font-family:inherit;padding:8px;border-radius:6px;border:1px solid #444;background:#1a1a24;color:#f5f5dc;}
  button{background:#facc15;color:#111;border:0;cursor:pointer;font-weight:700;}
  table{border-collapse:collapse;}
  td,th{border:1px solid #333;padding:6px 10px;}
`;

export const htmlBasicsSection: Section = {
  id: "html-basics",
  title: "HTML Foundations",
  emoji: "🧱",
  blurb: "Semantic markup — structure first, style later.",
  levels: [
    {
      id: "html-1",
      title: "Hello, Heading",
      emoji: "📰",
      difficulty: 1,
      language: "html",
      theory: "HTML uses tags like <h1>…<h6> for headings and <p> for paragraphs. The <h1> is the page's main title — there should be only one.",
      goal: "Add an <h1> with the text 'JS Quest' and a <p> below saying 'Learn by playing.'",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Write your HTML below -->\n`,
      steps: [
        { label: "Has exactly one <h1>", test: `document.querySelectorAll('h1').length === 1` },
        { label: "<h1> text is 'JS Quest'", test: `document.querySelector('h1')?.textContent.trim() === 'JS Quest'` },
        { label: "Has a <p> with the tagline", test: `Array.from(document.querySelectorAll('p')).some(p=>p.textContent.includes('Learn by playing'))` },
      ],
      hints: ["<h1>JS Quest</h1>", "<p>Learn by playing.</p>"],
      solution: `<h1>JS Quest</h1>\n<p>Learn by playing.</p>`,
      quiz: [
        { q: "Which tag is the main page heading?", options: ["<head>", "<h1>", "<title>", "<header>"], answer: 1 },
        { q: "How many <h1> per page (best practice)?", options: ["0", "1", "as many as you want", "exactly 6"], answer: 1 },
      ],
    },
    {
      id: "html-2",
      title: "Linking Out",
      emoji: "🔗",
      difficulty: 1,
      language: "html",
      theory: "Anchors <a href='URL'>label</a> create hyperlinks. Add target='_blank' to open in a new tab and rel='noopener' for safety.",
      goal: "Create a link to https://developer.mozilla.org with the text 'MDN', opening in a new tab.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Add the anchor here -->\n`,
      steps: [
        { label: "Has an <a>", test: `!!document.querySelector('a')` },
        { label: "href points to MDN", test: `document.querySelector('a')?.getAttribute('href') === 'https://developer.mozilla.org'` },
        { label: "Opens in a new tab", test: `document.querySelector('a')?.getAttribute('target') === '_blank'` },
        { label: "Link text is 'MDN'", test: `document.querySelector('a')?.textContent.trim() === 'MDN'` },
      ],
      hints: [`<a href="https://developer.mozilla.org" target="_blank" rel="noopener">MDN</a>`],
      solution: `<a href="https://developer.mozilla.org" target="_blank" rel="noopener">MDN</a>`,
      quiz: [{ q: "Which attribute opens a link in a new tab?", options: ["new", "target='_blank'", "open='new'", "href='_blank'"], answer: 1 }],
    },
    {
      id: "html-3",
      title: "Lists",
      emoji: "📋",
      difficulty: 1,
      language: "html",
      theory: "Use <ul> for unordered (bulleted) and <ol> for ordered (numbered) lists. Each item is an <li>.",
      goal: "Build an ordered list of 3 items: 'Plan', 'Code', 'Ship'.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Build the list -->\n`,
      steps: [
        { label: "Has an <ol>", test: `!!document.querySelector('ol')` },
        { label: "Has 3 <li> inside <ol>", test: `document.querySelectorAll('ol > li').length === 3` },
        { label: "Items in correct order", test: `Array.from(document.querySelectorAll('ol li')).map(l=>l.textContent.trim()).join(',') === 'Plan,Code,Ship'` },
      ],
      hints: ["<ol><li>Plan</li>...</ol>"],
      solution: `<ol>\n  <li>Plan</li>\n  <li>Code</li>\n  <li>Ship</li>\n</ol>`,
      quiz: [{ q: "Which produces a numbered list?", options: ["<ul>", "<ol>", "<list>", "<dl>"], answer: 1 }],
    },
    {
      id: "html-4",
      title: "Semantic Layout",
      emoji: "🏛️",
      difficulty: 2,
      language: "html",
      theory: "Use semantic tags — <header>, <nav>, <main>, <footer> — instead of generic <div>s. They help accessibility and SEO.",
      goal: "Build a page skeleton: <header> with <h1>'Site'</h1>, <nav>, <main>, <footer>.",
      previewCss: `${SHELL_CSS}\nheader,nav,main,footer{display:block;border:1px dashed #444;padding:8px;margin:6px 0;border-radius:6px;}`,
      starterCode: `<!-- Build the skeleton -->\n`,
      steps: [
        { label: "Has <header>", test: `!!document.querySelector('header')` },
        { label: "<h1> inside <header>", test: `document.querySelector('header h1')?.textContent.trim()==='Site'` },
        { label: "Has <nav>, <main>, <footer>", test: `!!document.querySelector('nav') && !!document.querySelector('main') && !!document.querySelector('footer')` },
      ],
      hints: ["<header><h1>Site</h1></header>"],
      solution: `<header><h1>Site</h1></header>\n<nav>links</nav>\n<main>content</main>\n<footer>© 2026</footer>`,
      quiz: [{ q: "Why use semantic tags?", options: ["shorter code", "accessibility & SEO", "they render faster", "they auto-style"], answer: 1 }],
    },
    {
      id: "html-5",
      title: "Forms 101",
      emoji: "📝",
      difficulty: 2,
      language: "html",
      theory: "Forms collect user input. Pair every <input> with a <label> via the `for` attribute matching the input's `id` for accessibility.",
      goal: "Build a form with a labeled email input (id='email', type='email', required) and a submit button labelled 'Sign up'.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Build the signup form -->\n`,
      steps: [
        { label: "Has a <form>", test: `!!document.querySelector('form')` },
        { label: "Email input correct", test: `const i=document.getElementById('email'); return !!i && i.type==='email' && i.required;` },
        { label: "Label binds to email", test: `document.querySelector('label[for=email]')!==null` },
        { label: "Submit button says 'Sign up'", test: `Array.from(document.querySelectorAll('button,input[type=submit]')).some(b => (b.textContent||b.value).trim()==='Sign up')` },
      ],
      hints: ["<label for='email'>Email</label><input id='email' type='email' required/>"],
      solution: `<form>\n  <label for="email">Email</label>\n  <input id="email" type="email" required/>\n  <button type="submit">Sign up</button>\n</form>`,
      quiz: [{ q: "What links a <label> to its input?", options: ["name", "id+for", "rel", "aria-label"], answer: 1 }],
    },
    {
      id: "html-6",
      title: "Image with Alt",
      emoji: "🖼️",
      difficulty: 1,
      language: "html",
      theory: "<img> needs `src` AND `alt`. Alt text describes the image for screen readers and shows when the image fails to load.",
      goal: "Add an image with src '/placeholder.svg' and alt text 'Cute placeholder'.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Add the image -->\n`,
      steps: [
        { label: "Has an <img>", test: `!!document.querySelector('img')` },
        { label: "src is /placeholder.svg", test: `document.querySelector('img')?.getAttribute('src') === '/placeholder.svg'` },
        { label: "alt is 'Cute placeholder'", test: `document.querySelector('img')?.getAttribute('alt') === 'Cute placeholder'` },
      ],
      hints: [`<img src="/placeholder.svg" alt="Cute placeholder" />`],
      solution: `<img src="/placeholder.svg" alt="Cute placeholder" />`,
      quiz: [{ q: "What's `alt` for?", options: ["title tooltip", "accessibility & fallback", "image format", "alignment"], answer: 1 }],
    },
    {
      id: "html-7",
      title: "Tables",
      emoji: "📊",
      difficulty: 2,
      language: "html",
      theory: "<table> uses <thead> + <tbody>. Header cells use <th>, data cells use <td>. Each row is a <tr>.",
      goal: "Build a 2-column table: header row 'Name' / 'Score', and one data row 'Ada' / '99'.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Build the table -->\n`,
      steps: [
        { label: "Has a <table>", test: `!!document.querySelector('table')` },
        { label: "<th> 'Name' and 'Score'", test: `const ths=[...document.querySelectorAll('th')].map(t=>t.textContent.trim()); return ths.includes('Name') && ths.includes('Score');` },
        { label: "<td> 'Ada' and '99'", test: `const tds=[...document.querySelectorAll('td')].map(t=>t.textContent.trim()); return tds.includes('Ada') && tds.includes('99');` },
      ],
      hints: ["<thead><tr><th>Name</th><th>Score</th></tr></thead>"],
      solution: `<table>\n  <thead><tr><th>Name</th><th>Score</th></tr></thead>\n  <tbody><tr><td>Ada</td><td>99</td></tr></tbody>\n</table>`,
      quiz: [{ q: "Header cell tag is…", options: ["<thead>", "<th>", "<td>", "<header>"], answer: 1 }],
    },
    {
      id: "html-8",
      title: "Select Dropdown",
      emoji: "🔽",
      difficulty: 2,
      language: "html",
      theory: "<select> with <option>s makes a dropdown. Add `selected` to pre-pick a value.",
      goal: "Build a select with id 'lang' offering 'JS', 'TS', 'Rust' — with 'TS' selected by default.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Build the dropdown -->\n`,
      steps: [
        { label: "<select id='lang'> exists", test: `!!document.getElementById('lang')` },
        { label: "Has 3 options", test: `document.querySelectorAll('#lang option').length === 3` },
        { label: "Default value is TS", test: `document.getElementById('lang')?.value === 'TS'` },
      ],
      hints: [`<select id="lang"><option>JS</option><option selected>TS</option><option>Rust</option></select>`],
      solution: `<select id="lang">\n  <option>JS</option>\n  <option selected>TS</option>\n  <option>Rust</option>\n</select>`,
      quiz: [{ q: "Pre-pick an option with…", options: ["default", "selected", "checked", "value"], answer: 1 }],
    },
    {
      id: "html-9",
      title: "Article + Aside",
      emoji: "📰",
      difficulty: 2,
      language: "html",
      theory: "<article> is self-contained content (a post). <aside> is tangential (a sidebar). Both improve document outline.",
      goal: "Build an <article> containing an <h2>'Post' and a <p>'Body', plus a sibling <aside>'Related'.",
      previewCss: `${SHELL_CSS}\narticle,aside{display:block;border:1px dashed #444;padding:8px;margin:6px 0;border-radius:6px;}`,
      starterCode: `<!-- Build the layout -->\n`,
      steps: [
        { label: "<article> with <h2>'Post'", test: `document.querySelector('article h2')?.textContent.trim()==='Post'` },
        { label: "<article> contains a <p>", test: `!!document.querySelector('article p')` },
        { label: "<aside> with text 'Related'", test: `document.querySelector('aside')?.textContent.includes('Related')` },
      ],
      hints: ["<article><h2>Post</h2><p>Body</p></article><aside>Related</aside>"],
      solution: `<article>\n  <h2>Post</h2>\n  <p>Body</p>\n</article>\n<aside>Related</aside>`,
      quiz: [{ q: "Self-contained content tag?", options: ["<section>", "<article>", "<div>", "<main>"], answer: 1 }],
    },
    {
      id: "html-10",
      title: "Accessible Button",
      emoji: "♿",
      difficulty: 3,
      language: "html",
      theory: "Use real <button> tags for actions. For icon-only buttons add `aria-label` so screen readers announce the purpose.",
      goal: "Create a button containing only the emoji ❤️, with aria-label 'Like'.",
      previewCss: SHELL_CSS,
      starterCode: `<!-- Accessible icon button -->\n`,
      steps: [
        { label: "Is a real <button>", test: `!!document.querySelector('button')` },
        { label: "Contains heart emoji", test: `document.querySelector('button')?.textContent.includes('❤')` },
        { label: "aria-label is 'Like'", test: `document.querySelector('button')?.getAttribute('aria-label')==='Like'` },
      ],
      hints: [`<button aria-label="Like">❤️</button>`],
      solution: `<button aria-label="Like">❤️</button>`,
      quiz: [{ q: "Why aria-label on icon buttons?", options: ["styling", "screen-reader announces purpose", "SEO", "tab order"], answer: 1 }],
    },
  ],
};
