import type { Section } from "../types";

export const modulesSection: Section = {
  id: "modules",
  title: "Modules, Iterators & Generators",
  emoji: "📦",
  blurb: "ES modules conceptually + Symbol.iterator + generators.",
  levels: [
    {
      id: "mod-1",
      title: "IIFE Module Pattern",
      emoji: "🛡️",
      difficulty: 2,
      theory: "Before ES Modules, devs used Immediately Invoked Function Expressions to create private scopes.",
      goal: "Build `Counter` via IIFE exposing `inc()` and `value()`. Internal count must NOT be accessible from outside.",
      starterCode: `// const Counter = (function(){ ... })();\n`,
      steps: [
        { label: "Counter.value() === 0 initially", test: `Counter.value() === 0` },
        { label: "After 2 inc, value === 2", test: `Counter.inc(); Counter.inc(); return Counter.value() === 2;` },
        { label: "No exposed count property", test: `Counter.count === undefined && Counter._count === undefined` },
      ],
      hints: ["let count=0; return { inc(){count++;}, value(){return count;} };"],
      solution: `const Counter = (function(){ let count=0; return { inc(){count++;}, value(){return count;} }; })();`,
      quiz: [{ q: "IIFEs primarily provide…", options: ["speed", "encapsulation", "inheritance", "JSX"], answer: 1 }],
    },
    {
      id: "mod-2",
      title: "Symbol.iterator",
      emoji: "♾️",
      difficulty: 3,
      theory: "Any object becomes iterable by defining `[Symbol.iterator]()` returning an `{ next() }` object.",
      goal: "Build `range(3)` returning an iterable yielding 0,1,2. `[...range(3)]` must equal [0,1,2].",
      starterCode: `function range(n){\n  // return iterable\n}\n`,
      steps: [
        { label: "Spread of range(3) is [0,1,2]", test: `JSON.stringify([...range(3)]) === '[0,1,2]'` },
        { label: "range(0) is empty", test: `JSON.stringify([...range(0)]) === '[]'` },
      ],
      hints: ["return { [Symbol.iterator](){ let i=0; return { next(){ return i<n ? {value:i++,done:false}:{value:undefined,done:true}; } }; } };"],
      solution: `function range(n){ return { [Symbol.iterator](){ let i=0; return { next(){ return i<n? {value:i++,done:false}:{value:undefined,done:true}; } }; } }; }`,
      quiz: [{ q: "for...of works on objects that implement…", options: ["toString", "Symbol.iterator", "valueOf", "Object.keys"], answer: 1 }],
    },
    {
      id: "mod-3",
      title: "Generators",
      emoji: "🌱",
      difficulty: 3,
      theory: "`function*` declares a generator. `yield` pauses and returns a value. Generators are iterable.",
      goal: "Generator `nats()` yields 1,2,3,… Take the first 4 into `first4 = [1,2,3,4]`.",
      starterCode: `function* nats(){\n  // yield 1, 2, 3, ...\n}\n// const first4 = ...\n`,
      steps: [
        { label: "first4 === [1,2,3,4]", test: `JSON.stringify(first4) === '[1,2,3,4]'` },
      ],
      hints: ["let n=1; while(true) yield n++;  then take first 4 with a loop."],
      solution: `function* nats(){ let n=1; while(true) yield n++; }\nconst first4=[]; const it=nats(); for(let i=0;i<4;i++) first4.push(it.next().value);`,
      quiz: [{ q: "yield does what?", options: ["returns and ends", "pauses and returns a value", "throws", "loops"], answer: 1 }],
    },
    {
      id: "mod-4",
      title: "Pure vs Impure Functions",
      emoji: "🧼",
      difficulty: 2,
      theory: "Pure functions: same input → same output, no side effects. Easier to test & reason about.",
      goal: "Refactor an impure function. Provide pure `addPure(arr, x)` returning a NEW array with x appended (do NOT mutate).",
      starterCode: `function addPure(arr, x){\n  // do not mutate arr\n}\n`,
      steps: [
        { label: "Returns new array", test: `(()=>{ const a=[1,2]; const b=addPure(a,3); return b!==a && JSON.stringify(b)==='[1,2,3]'; })()` },
        { label: "Original unchanged", test: `(()=>{ const a=[1,2]; addPure(a,3); return JSON.stringify(a)==='[1,2]'; })()` },
      ],
      hints: ["return [...arr, x];"],
      solution: `function addPure(arr,x){ return [...arr, x]; }`,
      quiz: [{ q: "Pure functions never…", options: ["return values", "have side effects", "use parameters", "use math"], answer: 1 }],
    },
  ],
};
