import type { Section } from "../types";

export const oopSection: Section = {
  id: "oop",
  title: "Object-Oriented JS",
  emoji: "🏛️",
  blurb: "Classes, inheritance, encapsulation, polymorphism.",
  levels: [
    {
      id: "oop-1",
      title: "Your First Class",
      emoji: "🏗️",
      difficulty: 1,
      theory: "`class` defines a blueprint. `constructor` runs on `new`. Methods live on the prototype.",
      goal: "Create class `Dog` with constructor(name) and method `bark()` returning `${name} says woof`.",
      starterCode: `class Dog {\n  // constructor + bark()\n}\n`,
      steps: [
        { label: "new Dog('Rex').bark() === 'Rex says woof'", test: `new Dog('Rex').bark() === 'Rex says woof'` },
        { label: "instance is a Dog", test: `(new Dog('A')) instanceof Dog` },
      ],
      hints: ["constructor(name){ this.name = name; } bark(){ return `${this.name} says woof`; }"],
      solution: `class Dog { constructor(name){ this.name=name; } bark(){ return \`\${this.name} says woof\`; } }`,
      quiz: [{ q: "Methods defined inside a class live on…", options: ["each instance", "the prototype", "the global scope", "window"], answer: 1 }],
    },
    {
      id: "oop-2",
      title: "Inheritance",
      emoji: "🧬",
      difficulty: 2,
      theory: "`extends` creates a subclass. Call `super(...)` in the child constructor.",
      goal: "Class `Animal` with `speak()` returning 'generic'. Class `Cat extends Animal` overrides speak() to return 'meow'.",
      starterCode: `class Animal {\n  speak(){ return 'generic'; }\n}\nclass Cat /* extends Animal */ {\n  // override speak\n}\n`,
      steps: [
        { label: "Cat instanceof Animal", test: `(new Cat()) instanceof Animal` },
        { label: "new Cat().speak() === 'meow'", test: `new Cat().speak() === 'meow'` },
        { label: "new Animal().speak() === 'generic'", test: `new Animal().speak() === 'generic'` },
      ],
      hints: ["class Cat extends Animal { speak(){ return 'meow'; } }"],
      solution: `class Animal{ speak(){return 'generic';} }\nclass Cat extends Animal{ speak(){return 'meow';} }`,
      quiz: [{ q: "Inside Cat constructor, you must call…", options: ["this()", "super()", "Animal.new()", "extend()"], answer: 1 }],
    },
    {
      id: "oop-3",
      title: "Encapsulation: Private Fields",
      emoji: "🔒",
      difficulty: 2,
      theory: "Prefix a field with `#` to make it truly private. Only the class can read/write it.",
      goal: "Class `BankAccount(initial)`: `#balance`, methods `deposit(n)`, `withdraw(n)` (no overdraft), `getBalance()`.",
      starterCode: `class BankAccount {\n  // #balance, deposit, withdraw, getBalance\n}\n`,
      steps: [
        { label: "Initial balance preserved", test: `new BankAccount(100).getBalance() === 100` },
        { label: "deposit increases balance", test: `(()=>{ const a=new BankAccount(0); a.deposit(50); return a.getBalance()===50; })()` },
        { label: "Cannot overdraw", test: `(()=>{ const a=new BankAccount(10); a.withdraw(50); return a.getBalance()===10; })()` },
      ],
      hints: ["if(n <= this.#balance) this.#balance -= n;"],
      solution: `class BankAccount{ #b; constructor(i){ this.#b=i; } deposit(n){ this.#b+=n; } withdraw(n){ if(n<=this.#b) this.#b-=n; } getBalance(){ return this.#b; } }`,
      quiz: [{ q: "Private fields use which prefix?", options: ["_", "#", "$", "private"], answer: 1 }],
    },
    {
      id: "oop-4",
      title: "Static Methods & Polymorphism",
      emoji: "🎭",
      difficulty: 3,
      theory: "`static` methods live on the class. Polymorphism: different classes implementing the same method shape.",
      goal: "Classes `Circle(r)` and `Square(s)` both expose `.area()`. Add static `Shape.totalArea(arr)` summing areas.",
      starterCode: `class Shape {\n  static totalArea(arr){\n    // sum areas\n  }\n}\nclass Circle {\n  // constructor + area()\n}\nclass Square {\n  // constructor + area()\n}\n`,
      steps: [
        { label: "Circle area", test: `Math.abs(new Circle(2).area() - Math.PI*4) < 1e-6` },
        { label: "Square area", test: `new Square(3).area() === 9` },
        { label: "Polymorphic sum", test: `Math.abs(Shape.totalArea([new Circle(1), new Square(2)]) - (Math.PI + 4)) < 1e-6` },
      ],
      hints: ["arr.reduce((s,x)=>s+x.area(), 0)"],
      solution: `class Shape{ static totalArea(a){ return a.reduce((s,x)=>s+x.area(),0); } }\nclass Circle{ constructor(r){this.r=r;} area(){return Math.PI*this.r*this.r;} }\nclass Square{ constructor(s){this.s=s;} area(){return this.s*this.s;} }`,
      quiz: [{ q: "Static methods are called on…", options: ["instances", "the class itself", "prototype chain", "window"], answer: 1 }],
    },
    {
      id: "oop-5",
      title: "Composition over Inheritance",
      emoji: "🧱",
      difficulty: 3,
      theory: "Instead of deep `extends` trees, COMPOSE behaviors via objects/functions. More flexible.",
      goal: "Build factory `createPlayer(name)` returning an object with `name`, `position:{x:0,y:0}`, and method `move(dx,dy)` mutating position.",
      starterCode: `function createPlayer(name){\n  // return composed object\n}\n`,
      steps: [
        { label: "Has name & position", test: `(()=>{ const p=createPlayer('Mia'); return p.name==='Mia' && p.position.x===0 && p.position.y===0; })()` },
        { label: "move updates position", test: `(()=>{ const p=createPlayer('M'); p.move(3,4); return p.position.x===3 && p.position.y===4; })()` },
      ],
      hints: ["return { name, position:{x:0,y:0}, move(dx,dy){ this.position.x+=dx; this.position.y+=dy; } };"],
      solution: `function createPlayer(name){ return { name, position:{x:0,y:0}, move(dx,dy){ this.position.x+=dx; this.position.y+=dy; } }; }`,
      quiz: [{ q: "Composition mainly favors…", options: ["deep inheritance trees", "small reusable behaviors", "global state", "classes only"], answer: 1 }],
    },
    {
      id: "oop-6",
      title: "Getters & Setters",
      emoji: "🎚️",
      difficulty: 2,
      theory: "`get`/`set` define computed-looking properties. Use them for validation or derived data.",
      goal: "Class `Temperature` has getter `celsius` and setter `celsius(v)` storing into #c. Add getter `fahrenheit` returning c*9/5+32.",
      starterCode: `class Temperature {\n  // #c, get/set celsius, get fahrenheit\n}\n`,
      steps: [
        { label: "set/get celsius round-trip", test: `(()=>{ const t=new Temperature(); t.celsius=20; return t.celsius===20; })()` },
        { label: "fahrenheit derived", test: `(()=>{ const t=new Temperature(); t.celsius=100; return t.fahrenheit===212; })()` },
      ],
      hints: ["get celsius(){ return this.#c; } set celsius(v){ this.#c = v; } get fahrenheit(){ return this.#c*9/5+32; }"],
      solution: `class Temperature{ #c=0; get celsius(){return this.#c;} set celsius(v){this.#c=v;} get fahrenheit(){return this.#c*9/5+32;} }`,
      quiz: [{ q: "Getters are accessed…", options: ["like methods t.x()", "like properties t.x", "via Reflect only", "via Symbol"], answer: 1 }],
    },
    {
      id: "oop-7",
      title: "Mixins",
      emoji: "🥣",
      difficulty: 3,
      theory: "Copy methods from one object to another to compose behavior across unrelated classes.",
      goal: "Define mixin `serializable = { toJSON(){ return JSON.stringify(this); } }`. Apply via Object.assign to a `Point({x,y})` instance.",
      starterCode: `const serializable = { toJSON(){ return JSON.stringify(this); } };\nclass Point { constructor(x,y){ this.x=x; this.y=y; } }\n// Mix it into Point.prototype\n`,
      steps: [
        { label: "Point instance can serialize", test: `(()=>{ const p=new Point(2,3); return p.toJSON() === '{"x":2,"y":3}'; })()` },
      ],
      hints: ["Object.assign(Point.prototype, serializable);"],
      solution: `const serializable={ toJSON(){ return JSON.stringify(this); } };\nclass Point{ constructor(x,y){ this.x=x; this.y=y; } }\nObject.assign(Point.prototype, serializable);`,
      quiz: [{ q: "Mixins enable…", options: ["multiple-inheritance-like sharing", "type checking", "private fields", "iteration"], answer: 0 }],
    },
  ],
};
