import type { Section } from "../types";

export const prototypesSection: Section = {
  id: "prototypes",
  title: "Prototypes & this",
  emoji: "🔗",
  blurb: "Prototype chain, this binding, call/apply/bind.",
  levels: [
    {
      id: "proto-1",
      title: "The Prototype Chain",
      emoji: "🪜",
      difficulty: 2,
      theory: "Every object has a hidden link to another object (its prototype). Method lookup walks up the chain.",
      goal: "Create object `parent = { greet(){ return 'hi'; } }` and `child = Object.create(parent)`. child.greet() should return 'hi'.",
      starterCode: `// const parent = ...\n// const child = ...\n`,
      steps: [
        { label: "child.greet() === 'hi'", test: `child.greet() === 'hi'` },
        { label: "Object.getPrototypeOf(child) === parent", test: `Object.getPrototypeOf(child) === parent` },
      ],
      hints: ["Object.create(parent) sets the prototype."],
      solution: `const parent = { greet(){ return 'hi'; } };\nconst child = Object.create(parent);`,
      quiz: [{ q: "Object.create(null) creates…", options: ["a normal object", "an object with NO prototype", "an Array", "throws"], answer: 1 }],
    },
    {
      id: "proto-2",
      title: "this in Methods",
      emoji: "👉",
      difficulty: 2,
      theory: "`this` inside a method = the object before the dot at call site. Detached methods lose this.",
      goal: "Build `counter = { n: 0, inc(){ this.n++; return this.n; } }`. Call it 3 times; counter.n must be 3.",
      starterCode: `// const counter = { n:0, inc(){ ... } };\n// call inc 3x\n`,
      steps: [
        { label: "counter.n === 3 after three inc()", test: `counter.n === 3` },
        { label: "inc returns the new value", test: `(()=>{ const c={n:0,inc(){ this.n++; return this.n; }}; return c.inc()===1 && c.inc()===2; })()` },
      ],
      hints: ["counter.inc(); counter.inc(); counter.inc();"],
      solution: `const counter = { n:0, inc(){ this.n++; return this.n; } };\ncounter.inc(); counter.inc(); counter.inc();`,
      quiz: [{ q: "Arrow functions inherit this from…", options: ["call site", "lexical (enclosing) scope", "global", "prototype"], answer: 1 }],
    },
    {
      id: "proto-3",
      title: "call, apply, bind",
      emoji: "🪝",
      difficulty: 3,
      theory: "`fn.call(thisArg, a, b)` runs immediately. `fn.apply(thisArg, [a,b])` uses an array. `fn.bind(thisArg)` returns a new bound function.",
      goal: "Define `function fullName(){ return this.first + ' ' + this.last; }`. Build `bound` bound to `{first:'Ada', last:'Lovelace'}`. bound() must return 'Ada Lovelace'.",
      starterCode: `function fullName(){ return this.first + ' ' + this.last; }\n// const bound = ...\n`,
      steps: [
        { label: "bound() === 'Ada Lovelace'", test: `bound() === 'Ada Lovelace'` },
        { label: "fullName.call({first:'Mae', last:'C'}) === 'Mae C'", test: `fullName.call({first:'Mae', last:'C'}) === 'Mae C'` },
      ],
      hints: ["fullName.bind({first:'Ada', last:'Lovelace'})"],
      solution: `function fullName(){ return this.first+' '+this.last; }\nconst bound = fullName.bind({first:'Ada',last:'Lovelace'});`,
      quiz: [{ q: "bind returns…", options: ["the result", "a new function", "undefined", "this"], answer: 1 }],
    },
    {
      id: "proto-4",
      title: "Extending Built-ins (carefully)",
      emoji: "🧪",
      difficulty: 3,
      theory: "You CAN add methods to built-in prototypes (e.g., Array.prototype.last). Use sparingly — risk of collisions.",
      goal: "Add `Array.prototype.last` returning the last element (no args). [1,2,3].last() must return 3.",
      starterCode: `// Array.prototype.last = function(){ ... }\n`,
      steps: [
        { label: "[1,2,3].last() === 3", test: `[1,2,3].last() === 3` },
        { label: "Empty array → undefined", test: `[].last() === undefined` },
      ],
      hints: ["return this[this.length-1];"],
      solution: `Array.prototype.last = function(){ return this[this.length-1]; };`,
      quiz: [{ q: "Modifying built-ins is risky because…", options: ["it's slow", "future specs/libs may collide", "it breaks JSON", "it freezes the object"], answer: 1 }],
    },
  ],
};
