import type { Section } from "../types";

export const solidSection: Section = {
  id: "solid",
  title: "SOLID Principles",
  emoji: "🧱",
  blurb: "Five principles for maintainable OO code.",
  levels: [
    {
      id: "solid-srp",
      title: "S — Single Responsibility",
      emoji: "1️⃣",
      difficulty: 2,
      theory: "A class/function should have ONE reason to change. Split mixed responsibilities.",
      goal: "Split a `User` God-class. Provide: class `User(name)` (data only) + class `UserPrinter` with `format(user)` returning `User: ${name}`.",
      starterCode: `class User {\n  // data only — name\n}\nclass UserPrinter {\n  // format(user)\n}\n`,
      steps: [
        { label: "User stores name only", test: `(()=>{ const u=new User('Ada'); return u.name==='Ada' && typeof u.format !== 'function'; })()` },
        { label: "UserPrinter formats", test: `new UserPrinter().format(new User('Ada')) === 'User: Ada'` },
      ],
      hints: ["Keep User minimal; put presentation in UserPrinter."],
      solution: `class User{ constructor(n){ this.name=n; } }\nclass UserPrinter{ format(u){ return 'User: '+u.name; } }`,
      quiz: [{ q: "SRP violation often shows as…", options: ["small classes", "classes that change for many reasons", "interfaces", "constants"], answer: 1 }],
    },
    {
      id: "solid-ocp",
      title: "O — Open / Closed",
      emoji: "2️⃣",
      difficulty: 3,
      theory: "Code should be OPEN for extension, CLOSED for modification. Add behavior via new types, not edits.",
      goal: "Implement `area(shape)` that calls `shape.area()` — no `if/else` over types. Provide `Square(s)` and `Triangle(b,h)` classes.",
      starterCode: `function area(shape){\n  // delegate, do not switch on type\n}\nclass Square { /* area() */ }\nclass Triangle { /* area() */ }\n`,
      steps: [
        { label: "Square area", test: `area(new Square(4)) === 16` },
        { label: "Triangle area", test: `area(new Triangle(4,5)) === 10` },
        { label: "No type switching", test: `!/typeof|instanceof|switch/.test(area.toString())`, hint: "Just call shape.area()." },
      ],
      hints: ["return shape.area();"],
      solution: `function area(s){ return s.area(); }\nclass Square{ constructor(s){this.s=s;} area(){return this.s*this.s;} }\nclass Triangle{ constructor(b,h){this.b=b;this.h=h;} area(){return 0.5*this.b*this.h;} }`,
      quiz: [{ q: "OCP encourages extension via…", options: ["editing existing code", "polymorphism", "global flags", "duplication"], answer: 1 }],
    },
    {
      id: "solid-lsp",
      title: "L — Liskov Substitution",
      emoji: "3️⃣",
      difficulty: 3,
      theory: "Subtypes must be usable wherever the base type is, without breaking expectations.",
      goal: "Class `Bird` with `fly()` returns 'flying'. Refactor to base `Bird` with `move()`, subclass `Sparrow` overrides `move()` returning 'flying'. Caller uses `move()`.",
      starterCode: `class Bird {\n  move(){ return 'moving'; }\n}\nclass Sparrow {\n  // extends Bird, override move\n}\n`,
      steps: [
        { label: "Sparrow extends Bird", test: `new Sparrow() instanceof Bird` },
        { label: "Sparrow.move() === 'flying'", test: `new Sparrow().move() === 'flying'` },
        { label: "Bird.move() unchanged", test: `new Bird().move() === 'moving'` },
      ],
      hints: ["class Sparrow extends Bird { move(){ return 'flying'; } }"],
      solution: `class Bird{ move(){return 'moving';} }\nclass Sparrow extends Bird{ move(){return 'flying';} }`,
      quiz: [{ q: "LSP is violated when…", options: ["subclass strengthens preconditions", "subclass adds methods", "base is abstract", "you use composition"], answer: 0 }],
    },
    {
      id: "solid-isp",
      title: "I — Interface Segregation",
      emoji: "4️⃣",
      difficulty: 2,
      theory: "Don't force clients to depend on methods they don't use. Prefer many small contracts.",
      goal: "Build two small mixins: `printer = { print(){return 'p';} }` and `scanner = { scan(){return 's';} }`. Compose `MFP` with both.",
      starterCode: `// printer, scanner, MFP\n`,
      steps: [
        { label: "printer.print() === 'p'", test: `printer.print() === 'p'` },
        { label: "scanner.scan() === 's'", test: `scanner.scan() === 's'` },
        { label: "MFP can print AND scan", test: `MFP.print() === 'p' && MFP.scan() === 's'` },
      ],
      hints: ["const MFP = Object.assign({}, printer, scanner);"],
      solution: `const printer={ print(){return 'p';} };\nconst scanner={ scan(){return 's';} };\nconst MFP = Object.assign({}, printer, scanner);`,
      quiz: [{ q: "ISP prefers…", options: ["one fat interface", "many focused interfaces", "no interfaces", "inheritance only"], answer: 1 }],
    },
    {
      id: "solid-dip",
      title: "D — Dependency Inversion",
      emoji: "5️⃣",
      difficulty: 3,
      theory: "High-level modules should depend on ABSTRACTIONS, not concrete implementations.",
      goal: "Class `Notifier(transport)` exposes `send(msg)` that returns `transport.deliver(msg)`. You can inject any transport object.",
      starterCode: `class Notifier {\n  // constructor(transport); send(msg)\n}\n`,
      steps: [
        { label: "Uses injected transport", test: `(()=>{ const fake={ deliver:m=>'sent:'+m }; return new Notifier(fake).send('hi') === 'sent:hi'; })()` },
        { label: "Works with another transport", test: `(()=>{ const t={ deliver:m=>m.toUpperCase() }; return new Notifier(t).send('ok') === 'OK'; })()` },
      ],
      hints: ["constructor(t){ this.t=t; } send(m){ return this.t.deliver(m); }"],
      solution: `class Notifier{ constructor(t){ this.t=t; } send(m){ return this.t.deliver(m); } }`,
      quiz: [{ q: "DIP injection improves…", options: ["coupling", "testability & flexibility", "memory use", "syntax"], answer: 1 }],
    },
  ],
};
